use math_audio_iir_fir::Biquad;
use ndarray::Array1;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Decomposed phase result: (minimum_phase, excess_phase, delay_ms, residual_phase)
pub type PhaseDecomposition = (Array1<f64>, Array1<f64>, f64, Array1<f64>);

/// Result of mixed-phase correction.
#[derive(Debug, Clone)]
pub struct MixedPhaseResult {
    /// IIR filters for minimum-phase correction (from standard PEQ optimizer)
    pub iir_filters: Vec<Biquad>,

    /// FIR coefficients for excess phase correction (short, pre-ringing constrained)
    pub fir_coefficients: Vec<f64>,

    /// Estimated propagation delay in milliseconds (from excess phase linear component)
    pub estimated_delay_ms: f64,

    /// Minimum phase reconstructed from magnitude
    pub minimum_phase: Array1<f64>,

    /// Excess phase (measured - minimum)
    pub excess_phase: Array1<f64>,

    /// Residual excess phase after removing linear delay
    pub residual_excess_phase: Array1<f64>,

    /// FIR filter length in taps
    pub fir_taps: usize,
}

/// Compact report for the excess-phase FIR generated by mixed-phase mode.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct MixedPhaseCorrectionReport {
    /// Linear propagation delay removed from excess phase before FIR design.
    pub estimated_delay_ms: f64,
    /// Number of coefficients in the generated excess-phase FIR.
    pub fir_taps: usize,
    /// Minimum residual excess phase after delay removal.
    pub residual_excess_phase_min_deg: f64,
    /// Maximum residual excess phase after delay removal.
    pub residual_excess_phase_max_deg: f64,
    /// RMS residual excess phase after delay removal.
    pub residual_excess_phase_rms_deg: f64,
}

impl MixedPhaseCorrectionReport {
    /// Summarize the exact residual phase used to generate an excess-phase FIR.
    pub fn from_residual(
        estimated_delay_ms: f64,
        fir_taps: usize,
        residual_excess_phase: &Array1<f64>,
    ) -> Self {
        let (minimum, maximum, sum_squares, count) = residual_excess_phase
            .iter()
            .copied()
            .filter(|value| value.is_finite())
            .fold(
                (f64::INFINITY, f64::NEG_INFINITY, 0.0, 0usize),
                |(minimum, maximum, sum_squares, count), value| {
                    (
                        minimum.min(value),
                        maximum.max(value),
                        sum_squares + value * value,
                        count + 1,
                    )
                },
            );
        let (minimum, maximum, rms) = if count == 0 {
            (0.0, 0.0, 0.0)
        } else {
            (minimum, maximum, (sum_squares / count as f64).sqrt())
        };

        Self {
            estimated_delay_ms,
            fir_taps,
            residual_excess_phase_min_deg: minimum,
            residual_excess_phase_max_deg: maximum,
            residual_excess_phase_rms_deg: rms,
        }
    }
}
