[package]
name = "autoeq"
version = "0.2.17"
edition = "2024"
description = "A library and tool for audio equalization and filter optimization"
repository = "https://github.com/pierreaubert/autoeq"
license = "GPL-3.0-or-later"
authors = ["Pierre F. Aubert"]
readme = "README.md"
documentation = "https://docs.rs/autoeq/"
keywords = ["iir", "peq", "speaker", "headphone", "optimisation"]
categories = ["science"]


[lib]
name = "autoeq"
path = "src/lib.rs"

[[bin]]
name = "autoeq"
path = "src/bin/autoeq.rs"

[[bin]]
name = "download"
path = "src/bin/download.rs"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[[bin]]
name = "plot_functions"
path = "src/bin/plot_functions.rs"

[dependencies]

# ndarray and dependencies: picky stuff
ndarray = { version = "0.16.0", features = ["blas"] }
blas-src = { version = "0.12.1", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
rand = "0.9.2"

# optimization library
nlopt = "0.8.1"
metaheuristics-nature = "10.1"

# plotting
plotly = { version = "0.13", features = ["static_export_default"] }
plotly_static = { version = "0.1", features = ["chromedriver", "webdriver_download"] }

# classical stuff
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1"
num_cpus = "1.16"
build_html = "2.7.0"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
signal-hook = "0.3"

