[package]
name = "eqopt"
version = "0.1.0"
edition = "2024"

[lib]
name = "eqopt"
path = "src/iir.rs"

[dependencies]
base64 = "0.21"
blas-src = { version = "0.8", features = ["accelerate"] }
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
ndarray = "0.15"
ndarray-linalg = { version = "0.16" }
nlopt = "0.8.1"
plotly = { version = "0.13", features = ["static_export_default"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1"

[build-dependencies]
cmake = "0.1.54"

[env]
CMAKE_CONFIGURE_ARGS = "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
