[target.x86_64-unknown-linux-gnu]
dockerfile = "./builds/Dockerfile.x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./builds/Dockerfile.aarch64-unknown-linux-gnu"

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:main"

[target.aarch64-pc-windows-gnu]
image = "ghcr.io/cross-rs/aarch64-pc-windows-gnu:main"
