// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::{ObjectiveData, ObjectiveDataBuilder};
use super::misc::MIN_DE_GENERATIONS;
use super::types::setup_de_common;
use ndarray::Array1;

use crate::PeqModel;
use ndarray::array;

fn test_objective_data() -> ObjectiveData {
    ObjectiveDataBuilder::speaker_flat(
        array![100.0, 1000.0],
        Array1::zeros(2),
        Array1::zeros(2),
        48_000.0,
        PeqModel::Pk,
    )
    .max_db(6.0)
    .min_db(0.0)
    .freq_range(20.0, 20_000.0)
    .smoothing(false, 2)
    .build()
    .expect("valid test objective data")
}

#[test]
fn setup_de_common_clamps_to_maxeval_when_budget_is_small() {
    // B6 — when maxeval is smaller than MIN_DE_GENERATIONS × pop_size,
    // the floor is disabled so user intent is honoured.
    let lower_bounds = vec![-1.0, -1.0];
    let upper_bounds = vec![1.0, 1.0];
    let setup = setup_de_common(
        &lower_bounds,
        &upper_bounds,
        test_objective_data(),
        20,
        55,
        true,
    );

    assert_eq!(setup.population_size, 20);
    assert!(
        setup.max_iter < MIN_DE_GENERATIONS,
        "tiny maxeval must cap max_iter below the floor, got {}",
        setup.max_iter,
    );
    assert!(setup.max_iter >= 1);
    // Review P3: total evals must not drift past 2 × maxeval.
    let total_evals = setup.population_size + setup.max_iter * setup.population_size;
    assert!(
        total_evals <= 2 * 55,
        "total evals {} must not exceed 2 × maxeval (={})",
        total_evals,
        2 * 55
    );
}

#[test]
fn setup_de_common_honours_maxeval_equal_to_popsize() {
    // Review edge case: maxeval == pop_size. Previously `computed.max(1)`
    // ran 1 generation × pop_size evals + pop_size seed = 2 × budget.
    let lower_bounds = vec![-1.0, -1.0];
    let upper_bounds = vec![1.0, 1.0];
    let setup = setup_de_common(
        &lower_bounds,
        &upper_bounds,
        test_objective_data(),
        20,
        20,
        true,
    );
    assert_eq!(setup.max_iter, 1);
}

#[test]
fn setup_de_common_respects_large_maxeval() {
    let lower_bounds = vec![-1.0, -1.0, -1.0];
    let upper_bounds = vec![1.0, 1.0, 1.0];
    let setup = setup_de_common(
        &lower_bounds,
        &upper_bounds,
        test_objective_data(),
        20,
        1_000_000,
        true,
    );

    // With large maxeval, computed generations should exceed MIN_DE_GENERATIONS
    assert!(setup.max_iter >= MIN_DE_GENERATIONS);
    // Check actual generation count: (1_000_000 - pop_size) / pop_size
    let expected = (1_000_000 - setup.population_size) / setup.population_size;
    assert_eq!(setup.max_iter, expected);
}
