[package]
name = "autoeq-workflow"
version = "0.5.5"
edition = "2024"
description = "Speaker and headphone AutoEQ workflows"
license = "GPL-3.0-or-later"
documentation = "https://docs.rs/autoeq-workflow"
homepage = "https://github.com/pierreaubert/autoeq"

[lints]
workspace = true

[dependencies]
autoeq-core = { workspace = true }
autoeq-measurements = { workspace = true }
autoeq-optim = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
hound = { workspace = true }
log = { workspace = true }
ndarray = { workspace = true }
num_cpus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tokio = { workspace = true }
