// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::super::*;
use super::types::SubDriverInfo;
use super::types::SubPreprocessResult;

/// Preprocess the LFE channel's SpeakerConfig into a combined curve and per-driver info.
///
/// Dispatches by SpeakerConfig variant:
/// - Single: load curve, no drivers
/// - MultiSub + Mso: run MSO optimization, return combined + per-sub gains/delays
/// - MultiSub + Single: average all subs, return combined + per-sub info (zero gains/delays)
/// - MultiSub + Dba: error (should use SpeakerConfig::Dba)
/// - Cardioid: simulate combined response from front + delayed/inverted rear
/// - Dba: run DBA optimization, return combined + front/rear info
/// - Group: error (handled by generic path)
pub(in super::super) fn preprocess_sub(
    lfe_config: &SpeakerConfig,
    strategy: &SubwooferStrategy,
    optimizer: &crate::roomeq::types::OptimizerConfig,
    sample_rate: f64,
) -> Result<SubPreprocessResult> {
    match lfe_config {
        SpeakerConfig::Single(source) => {
            let curve = load_source(source).map_err(|e| AutoeqError::InvalidMeasurement {
                message: e.to_string(),
            })?;
            Ok(SubPreprocessResult {
                combined_curve: curve,
                drivers: None,
            })
        }
        SpeakerConfig::MultiSub(ms) => match strategy {
            SubwooferStrategy::Mso => preprocess_multisub_mso(ms, optimizer, sample_rate),
            SubwooferStrategy::Single => preprocess_multisub_independent(ms),
            SubwooferStrategy::Dba => Err(AutoeqError::InvalidConfiguration {
                message: "SubwooferStrategy::Dba requires SpeakerConfig::Dba, not MultiSub"
                    .to_string(),
            }),
        },
        SpeakerConfig::Cardioid(c) => preprocess_cardioid(c),
        SpeakerConfig::Dba(d) => preprocess_dba(d, optimizer, sample_rate),
        SpeakerConfig::Group(_) => Err(AutoeqError::InvalidConfiguration {
            message: "Group speaker config should not reach stereo sub workflow; use generic path"
                .to_string(),
        }),
        SpeakerConfig::SupportingSource(_) => Err(AutoeqError::InvalidConfiguration {
            message: "Supporting source config cannot be used as an LFE/subwoofer channel"
                .to_string(),
        }),
    }
}

/// MSO: optimize inter-sub gains/delays, return combined curve + per-sub info
pub(in super::super) fn preprocess_multisub_mso(
    ms: &MultiSubGroup,
    optimizer: &crate::roomeq::types::OptimizerConfig,
    sample_rate: f64,
) -> Result<SubPreprocessResult> {
    info!("  MSO optimization for {} subwoofers", ms.subwoofers.len());

    let (result, combined) =
        crate::roomeq::multisub::optimize_multisub(&ms.subwoofers, optimizer, sample_rate)
            .map_err(|e| AutoeqError::OptimizationFailed {
                message: format!("MSO optimization failed: {}", e),
            })?;

    info!(
        "  MSO result: gains={:?}, delays={:?}",
        result.gains, result.delays
    );

    // Load individual curves for driver info
    let mut drivers = Vec::new();
    for (i, source) in ms.subwoofers.iter().enumerate() {
        let curve = load_source(source).map_err(|e| AutoeqError::InvalidMeasurement {
            message: e.to_string(),
        })?;
        drivers.push(SubDriverInfo {
            name: format!("{}_{}", ms.name, i + 1),
            gain: result.gains.get(i).copied().unwrap_or(0.0),
            delay: result.delays.get(i).copied().unwrap_or(0.0),
            inverted: false,
            initial_curve: Some(curve),
        });
    }

    Ok(SubPreprocessResult {
        combined_curve: combined,
        drivers: Some(drivers),
    })
}

/// Independent subs: average all sub curves, return combined + per-sub info (zero gains/delays)
pub(in super::super) fn preprocess_multisub_independent(
    ms: &MultiSubGroup,
) -> Result<SubPreprocessResult> {
    info!(
        "  Independent sub averaging for {} subwoofers",
        ms.subwoofers.len()
    );

    let mut curves = Vec::new();
    for source in &ms.subwoofers {
        let curve = load_source(source).map_err(|e| AutoeqError::InvalidMeasurement {
            message: e.to_string(),
        })?;
        curves.push(curve);
    }

    // Power summation on the first sub's frequency grid:
    // Convert dB to linear power, sum, convert back to dB.
    // This correctly represents incoherent summation of multiple subs.
    let ref_freq = curves[0].freq.clone();
    let mut sum_power = ndarray::Array1::<f64>::zeros(ref_freq.len());
    for curve in &curves {
        let interp = crate::read::interpolate_log_space(&ref_freq, curve);
        sum_power += &interp.spl.mapv(|db| 10.0_f64.powf(db / 10.0));
    }
    let avg_spl = sum_power.mapv(|p| 10.0 * p.log10());

    let combined = Curve {
        freq: ref_freq,
        spl: avg_spl,
        phase: None,
        ..Default::default()
    };

    let drivers: Vec<SubDriverInfo> = curves
        .into_iter()
        .enumerate()
        .map(|(i, curve)| SubDriverInfo {
            name: format!("{}_{}", ms.name, i + 1),
            gain: 0.0,
            delay: 0.0,
            inverted: false,
            initial_curve: Some(curve),
        })
        .collect();

    Ok(SubPreprocessResult {
        combined_curve: combined,
        drivers: Some(drivers),
    })
}

/// Cardioid: simulate combined response from front + delayed/inverted rear sub
pub(in super::super) fn preprocess_cardioid(c: &CardioidConfig) -> Result<SubPreprocessResult> {
    let front_curve = load_source(&c.front).map_err(|e| AutoeqError::InvalidMeasurement {
        message: format!("Cardioid front: {}", e),
    })?;
    let rear_curve = load_source(&c.rear).map_err(|e| AutoeqError::InvalidMeasurement {
        message: format!("Cardioid rear: {}", e),
    })?;

    if !crate::roomeq::frequency_grid::is_valid_frequency_grid(&front_curve.freq)
        || !crate::roomeq::frequency_grid::is_valid_frequency_grid(&rear_curve.freq)
    {
        return Err(AutoeqError::InvalidMeasurement {
            message: "Cardioid preprocessing requires valid frequency grids".to_string(),
        });
    }
    if front_curve.spl.len() != front_curve.freq.len()
        || rear_curve.spl.len() != rear_curve.freq.len()
        || front_curve
            .phase
            .as_ref()
            .is_some_and(|phase| phase.len() != front_curve.freq.len())
        || rear_curve
            .phase
            .as_ref()
            .is_some_and(|phase| phase.len() != rear_curve.freq.len())
    {
        return Err(AutoeqError::InvalidMeasurement {
            message: "Cardioid preprocessing curve arrays must match frequency-grid length"
                .to_string(),
        });
    }
    if !crate::roomeq::frequency_grid::same_frequency_grid(&front_curve.freq, &rear_curve.freq) {
        return Err(AutoeqError::InvalidMeasurement {
            message: "Cardioid preprocessing requires front and rear curves to share the same frequency grid".to_string(),
        });
    }

    let delay_ms = c.separation_meters / 343.0 * 1000.0;
    info!(
        "  Cardioid: separation={:.2}m, delay={:.2}ms",
        c.separation_meters, delay_ms
    );

    // Simulate combined response (complex sum of front + delayed/inverted rear)
    use num_complex::Complex;
    let n_points = front_curve.freq.len();
    let mut combined_spl = ndarray::Array1::zeros(n_points);

    let front_phase_zeros = ndarray::Array1::zeros(n_points);
    let rear_phase_zeros = ndarray::Array1::zeros(n_points);
    let front_phase = front_curve.phase.as_ref().unwrap_or(&front_phase_zeros);
    let rear_phase = rear_curve.phase.as_ref().unwrap_or(&rear_phase_zeros);

    for i in 0..n_points {
        let f = front_curve.freq[i];
        let omega = 2.0 * std::f64::consts::PI * f;

        // Front
        let f_mag = 10.0_f64.powf(front_curve.spl[i] / 20.0);
        let f_phi = front_phase[i].to_radians();
        let f_c = Complex::from_polar(f_mag, f_phi);

        // Rear (Inverted + Delayed)
        let r_mag = 10.0_f64.powf(rear_curve.spl[i] / 20.0);
        let r_phi_meas = rear_phase[i].to_radians();
        let delay_s = delay_ms / 1000.0;
        let delay_phi = -omega * delay_s;
        let invert_phi = std::f64::consts::PI;
        let r_phi_total = r_phi_meas + delay_phi + invert_phi;
        let r_c = Complex::from_polar(r_mag, r_phi_total);

        let sum = f_c + r_c;
        combined_spl[i] = 20.0 * sum.norm().log10();
    }

    let combined = Curve {
        freq: front_curve.freq.clone(),
        spl: combined_spl,
        phase: None,
        ..Default::default()
    };

    let drivers = vec![
        SubDriverInfo {
            name: "Front Sub".to_string(),
            gain: 0.0,
            delay: 0.0,
            inverted: false,
            initial_curve: Some(front_curve),
        },
        SubDriverInfo {
            name: "Rear Sub".to_string(),
            gain: 0.0,
            delay: delay_ms,
            inverted: true,
            initial_curve: Some(rear_curve),
        },
    ];

    Ok(SubPreprocessResult {
        combined_curve: combined,
        drivers: Some(drivers),
    })
}

/// DBA: run DBA optimization, return combined curve + front/rear driver info
pub(in super::super) fn preprocess_dba(
    d: &DBAConfig,
    optimizer: &crate::roomeq::types::OptimizerConfig,
    sample_rate: f64,
) -> Result<SubPreprocessResult> {
    info!("  DBA optimization");

    let (result, combined) = dba::optimize_dba(d, optimizer, sample_rate).map_err(|e| {
        AutoeqError::OptimizationFailed {
            message: format!("DBA optimization failed: {}", e),
        }
    })?;

    info!(
        "  DBA result: gains={:?}, delays={:?}",
        result.gains, result.delays
    );

    // Load front and rear array responses for display
    let front_curve =
        dba::sum_array_response(&d.front).map_err(|e| AutoeqError::InvalidMeasurement {
            message: format!("DBA front array: {}", e),
        })?;
    let rear_curve =
        dba::sum_array_response(&d.rear).map_err(|e| AutoeqError::InvalidMeasurement {
            message: format!("DBA rear array: {}", e),
        })?;

    let drivers = vec![
        SubDriverInfo {
            name: "Front Array".to_string(),
            gain: result.gains.first().copied().unwrap_or(0.0),
            delay: result.delays.first().copied().unwrap_or(0.0),
            inverted: false,
            initial_curve: Some(front_curve),
        },
        SubDriverInfo {
            name: "Rear Array".to_string(),
            gain: result.gains.get(1).copied().unwrap_or(0.0),
            delay: result.delays.get(1).copied().unwrap_or(0.0),
            inverted: true,
            initial_curve: Some(rear_curve),
        },
    ];

    Ok(SubPreprocessResult {
        combined_curve: combined,
        drivers: Some(drivers),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Curve;
    use crate::MeasurementSource;
    use crate::roomeq::types::{
        CardioidConfig, DBAConfig, MultiSubGroup, OptimizerConfig, SpeakerConfig, SpeakerGroup,
        SubwooferStrategy,
    };

    fn make_curve(freq_count: usize, spl_db: f64, phase_deg: Option<f64>) -> Curve {
        let freq = ndarray::Array1::logspace(10.0, f64::log10(20.0), f64::log10(200.0), freq_count);
        let spl = ndarray::Array1::from_elem(freq_count, spl_db);
        let phase = phase_deg.map(|p| ndarray::Array1::from_elem(freq_count, p));
        Curve {
            freq,
            spl,
            phase,
            ..Default::default()
        }
    }

    fn tiny_optimizer() -> OptimizerConfig {
        OptimizerConfig {
            algorithm: "autoeq:cobyla".to_string(),
            max_iter: 20,
            population: 6,
            min_freq: 20.0,
            max_freq: 200.0,
            seed: Some(1),
            ..Default::default()
        }
    }

    #[test]
    fn preprocess_sub_single_returns_finite_combined_curve() {
        let curve = make_curve(16, 80.0, None);
        let config = SpeakerConfig::Single(MeasurementSource::InMemory(curve));
        let result = preprocess_sub(
            &config,
            &SubwooferStrategy::Single,
            &tiny_optimizer(),
            48000.0,
        );
        assert!(result.is_ok(), "expected Ok, got Err: {:?}", result.err());
        let result = result.unwrap();
        assert!(result.drivers.is_none());
        assert!(result.combined_curve.spl.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn preprocess_sub_multisub_mso_returns_drivers() {
        let subs = MultiSubGroup {
            name: "subs".to_string(),
            speaker_name: None,
            subwoofers: vec![
                MeasurementSource::InMemory(make_curve(16, 80.0, Some(0.0))),
                MeasurementSource::InMemory(make_curve(16, 80.0, Some(0.0))),
            ],
            allpass_optimization: false,
        };
        let config = SpeakerConfig::MultiSub(subs);
        let result = preprocess_sub(&config, &SubwooferStrategy::Mso, &tiny_optimizer(), 48000.0);
        assert!(result.is_ok(), "expected Ok, got Err: {:?}", result.err());
        let result = result.unwrap();
        assert!(result.drivers.is_some());
        let drivers = result.drivers.unwrap();
        assert!(!drivers.is_empty());
        assert!(result.combined_curve.spl.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn preprocess_sub_multisub_single_averages_subs() {
        let subs = MultiSubGroup {
            name: "subs".to_string(),
            speaker_name: None,
            subwoofers: vec![
                MeasurementSource::InMemory(make_curve(16, 80.0, None)),
                MeasurementSource::InMemory(make_curve(16, 80.0, None)),
            ],
            allpass_optimization: false,
        };
        let config = SpeakerConfig::MultiSub(subs);
        let result = preprocess_sub(
            &config,
            &SubwooferStrategy::Single,
            &tiny_optimizer(),
            48000.0,
        );
        assert!(result.is_ok(), "expected Ok, got Err: {:?}", result.err());
        let result = result.unwrap();
        assert!(result.drivers.is_some());
        let drivers = result.drivers.unwrap();
        assert_eq!(drivers.len(), 2);
        assert!(drivers.iter().all(|d| d.gain == 0.0 && d.delay == 0.0));
        assert!(result.combined_curve.spl.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn preprocess_sub_group_returns_error() {
        let group = SpeakerGroup {
            name: "group".to_string(),
            speaker_name: None,
            measurements: vec![MeasurementSource::InMemory(make_curve(16, 80.0, None))],
            crossover: None,
        };
        let config = SpeakerConfig::Group(group);
        let result = preprocess_sub(
            &config,
            &SubwooferStrategy::Single,
            &tiny_optimizer(),
            48000.0,
        );
        assert!(result.is_err(), "expected Err for Group config");
    }

    #[test]
    fn preprocess_cardioid_happy_path_with_phase() {
        let front = make_curve(16, 80.0, Some(0.0));
        let rear = make_curve(16, 80.0, Some(0.0));
        let config = CardioidConfig {
            name: "cardioid".to_string(),
            speaker_name: None,
            front: MeasurementSource::InMemory(front),
            rear: MeasurementSource::InMemory(rear),
            separation_meters: 1.0,
        };
        let result = preprocess_cardioid(&config);
        assert!(result.is_ok(), "expected Ok, got Err: {:?}", result.err());
        let result = result.unwrap();
        assert!(result.drivers.is_some());
        assert_eq!(result.drivers.as_ref().unwrap().len(), 2);
        assert!(result.combined_curve.spl.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn preprocess_cardioid_errors_on_mismatched_frequency_grids() {
        let mut front = make_curve(16, 80.0, Some(0.0));
        let rear = make_curve(16, 80.0, Some(0.0));
        front.freq = ndarray::Array1::logspace(10.0, f64::log10(25.0), f64::log10(205.0), 16);
        let config = CardioidConfig {
            name: "cardioid".to_string(),
            speaker_name: None,
            front: MeasurementSource::InMemory(front),
            rear: MeasurementSource::InMemory(rear),
            separation_meters: 1.0,
        };
        let result = preprocess_cardioid(&config);
        assert!(result.is_err(), "expected Err for mismatched grids");
    }

    #[test]
    fn preprocess_cardioid_errors_on_mismatched_spl_lengths() {
        let mut front = make_curve(16, 80.0, Some(0.0));
        front.spl = ndarray::Array1::from_elem(8, 80.0);
        let rear = make_curve(16, 80.0, Some(0.0));
        let config = CardioidConfig {
            name: "cardioid".to_string(),
            speaker_name: None,
            front: MeasurementSource::InMemory(front),
            rear: MeasurementSource::InMemory(rear),
            separation_meters: 1.0,
        };
        let result = preprocess_cardioid(&config);
        assert!(result.is_err(), "expected Err for mismatched SPL lengths");
    }

    #[test]
    fn preprocess_cardioid_errors_on_mismatched_phase_lengths() {
        let mut front = make_curve(16, 80.0, Some(0.0));
        front.phase = Some(ndarray::Array1::from_elem(8, 0.0));
        let rear = make_curve(16, 80.0, Some(0.0));
        let config = CardioidConfig {
            name: "cardioid".to_string(),
            speaker_name: None,
            front: MeasurementSource::InMemory(front),
            rear: MeasurementSource::InMemory(rear),
            separation_meters: 1.0,
        };
        let result = preprocess_cardioid(&config);
        assert!(result.is_err(), "expected Err for mismatched phase lengths");
    }

    #[test]
    fn preprocess_dba_happy_path() {
        let front_curve = make_curve(16, 80.0, Some(0.0));
        let rear_curve = make_curve(16, 80.0, Some(0.0));
        let config = DBAConfig {
            name: "dba".to_string(),
            speaker_name: None,
            front: vec![MeasurementSource::InMemory(front_curve)],
            rear: vec![MeasurementSource::InMemory(rear_curve)],
        };
        let result = preprocess_dba(&config, &tiny_optimizer(), 48000.0);
        assert!(result.is_ok(), "expected Ok, got Err: {:?}", result.err());
        let result = result.unwrap();
        assert!(result.drivers.is_some());
        assert_eq!(result.drivers.as_ref().unwrap().len(), 2);
        assert!(result.combined_curve.spl.iter().all(|v| v.is_finite()));
    }
}
