[package]
name = "autoeq"
version = "0.2.211"
edition = "2021"
authors = ["Pierre Aubert <pierre@spinorama.org>"]
license = "GPL-3.0-or-later"
description = "Automatic equalization for speakers and headphones"
repository = "https://github.com/pierreaubert/autoeq"

[dependencies]
build_html = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
ndarray = { workspace = true }
nlopt = { workspace = true }
num_cpus = { workspace = true }
metaheuristics-nature = { workspace = true }
plotly = { workspace = true }
plotly_static = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
signal-hook-tokio = { workspace = true }
tokio = { workspace = true }
urlencoding = { workspace = true }

# AutoEQ crates
autoeq-iir = { path = "../src-iir" }
autoeq-de = { path = "../src-de" }
autoeq-cea2034 = { path = "../src-cea2034" }
autoeq-env = { path = "../src-env" }

# External BLAS - using Apple Accelerate on macOS
blas-src = { workspace = true }
# openblas-src = { workspace = true }  # Commented out in favor of Accelerate

[[bin]]
name = "autoeq"
path = "bin/autoeq.rs"

[[bin]]
name = "benchmark"
path = "bin/benchmark.rs"

[[bin]]
name = "download"
path = "bin/download.rs"

[lib]
name = "autoeq"
path = "src/lib.rs"
