// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::misc::smooth_log_frequency;
use super::spatial_robustness_config::SpatialRobustnessConfig;
use super::spatial_robustness_config::correction_depth_mask;
use ndarray::Array1;

mod misc;

#[test]
fn test_correction_depth_low_variance() {
    let freq = Array1::from_vec(vec![100.0]);
    let variance = Array1::from_vec(vec![0.5]); // well below threshold
    let config = SpatialRobustnessConfig {
        mask_smoothing_octaves: 0.0, // disable smoothing for test
        ..Default::default()
    };

    let depth = correction_depth_mask(&freq, &variance, &config);
    // sigmoid((3.0 - 0.5) / 2.0) = sigmoid(1.25) ≈ 0.777
    // depth = 0.1 + 0.9 * 0.777 ≈ 0.80
    assert!(
        depth[0] > 0.75,
        "low variance should give high correction, got {}",
        depth[0]
    );
}

#[test]
fn test_correction_depth_high_variance() {
    let freq = Array1::from_vec(vec![100.0]);
    let variance = Array1::from_vec(vec![10.0]); // well above threshold
    let config = SpatialRobustnessConfig {
        mask_smoothing_octaves: 0.0,
        ..Default::default()
    };

    let depth = correction_depth_mask(&freq, &variance, &config);
    assert!(
        depth[0] < 0.3,
        "high variance should give reduced correction, got {}",
        depth[0]
    );
    assert!(
        depth[0] >= config.min_correction_depth,
        "should never go below min_correction_depth"
    );
}

#[test]
fn test_correction_depth_allows_zero_when_configured() {
    let freq = Array1::from_vec(vec![100.0]);
    let variance = Array1::from_vec(vec![10.0]);
    let config = SpatialRobustnessConfig {
        transition_width_db: 0.0,
        min_correction_depth: 0.0,
        mask_smoothing_octaves: 0.0,
        ..Default::default()
    };

    let depth = correction_depth_mask(&freq, &variance, &config);

    assert_eq!(depth[0], 0.0);
}

#[test]
fn test_correction_depth_at_threshold() {
    let freq = Array1::from_vec(vec![100.0]);
    let variance = Array1::from_vec(vec![3.0]); // exactly at threshold
    let config = SpatialRobustnessConfig {
        mask_smoothing_octaves: 0.0,
        ..Default::default()
    };

    let depth = correction_depth_mask(&freq, &variance, &config);
    // At threshold, sigmoid(0) = 0.5, so depth = min + (1-min)*0.5
    let expected = 0.1 + 0.9 * 0.5;
    assert!(
        (depth[0] - expected).abs() < 0.01,
        "expected ~{:.2}, got {:.2}",
        expected,
        depth[0]
    );
}

#[test]
fn test_correction_depth_zero_transition_width() {
    // Bug fix: transition_width_db = 0.0 should use hard threshold (not divide by zero)
    let freq = Array1::from_vec(vec![100.0, 200.0]);
    let variance = Array1::from_vec(vec![1.0, 5.0]); // below and above threshold
    let config = SpatialRobustnessConfig {
        variance_threshold_db: 3.0,
        transition_width_db: 0.0, // hard threshold
        min_correction_depth: 0.1,
        mask_smoothing_octaves: 0.0,
    };

    let depth = correction_depth_mask(&freq, &variance, &config);

    // Below threshold → full correction
    assert!(
        depth[0] > 0.9,
        "below threshold should give full correction, got {}",
        depth[0]
    );
    // Above threshold → min correction
    assert!(
        (depth[1] - 0.1).abs() < 0.01,
        "above threshold should give min correction, got {}",
        depth[1]
    );
}

#[test]
fn test_smooth_log_frequency_reduces_variation() {
    // Smoothing should reduce rapid oscillations
    // Use wider frequency span so the window doesn't cover everything
    let freq = Array1::from_vec(vec![
        50.0, 70.0, 100.0, 140.0, 200.0, 280.0, 400.0, 560.0, 800.0, 1120.0, 1600.0,
    ]);
    let data = Array1::from_vec(vec![1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]);

    let smoothed = smooth_log_frequency(&data, &freq, 1.5); // 1.5 octave window

    // Smoothed should have less variation than original
    let orig_range = 1.0;
    let smooth_range = smoothed.iter().cloned().fold(f64::NEG_INFINITY, f64::max)
        - smoothed.iter().cloned().fold(f64::INFINITY, f64::min);
    assert!(
        smooth_range < orig_range,
        "smoothing should reduce range: orig={:.2}, smoothed={:.2}",
        orig_range,
        smooth_range
    );
}

#[test]
fn test_smooth_log_frequency_preserves_constant() {
    // Smoothing a constant array should return the same constant
    let freq = Array1::from_vec(vec![100.0, 200.0, 400.0, 800.0]);
    let data = Array1::from_vec(vec![0.5, 0.5, 0.5, 0.5]);
    let smoothed = smooth_log_frequency(&data, &freq, 1.0);
    for &v in smoothed.iter() {
        assert!((v - 0.5).abs() < 0.001);
    }
}

// ---------------------------------------------------------------------------
// Tests for spatial_robustness/analyze.rs
// ---------------------------------------------------------------------------

fn make_spatial_curve(spl_offset: f64) -> crate::Curve {
    crate::Curve {
        freq: Array1::from_vec(vec![100.0, 200.0, 400.0, 800.0, 1600.0]),
        spl: Array1::from_vec(vec![
            80.0 + spl_offset,
            82.0 + spl_offset,
            81.0 + spl_offset,
            83.0 + spl_offset,
            80.0 + spl_offset,
        ]),
        phase: None,
        ..Default::default()
    }
}

#[test]
fn analyze_spatial_robustness_basic() {
    use super::analyze::analyze_spatial_robustness;

    let curves = vec![make_spatial_curve(0.0), make_spatial_curve(1.0), make_spatial_curve(-1.0)];
    let config = SpatialRobustnessConfig::default();
    let result = analyze_spatial_robustness(&curves, &config).unwrap();
    assert_eq!(result.averaged_curve.freq.len(), curves[0].freq.len());
    assert_eq!(result.spatial_variance.len(), curves[0].freq.len());
    assert_eq!(result.correction_depth.len(), curves[0].freq.len());
}

#[test]
fn analyze_spatial_robustness_weighted() {
    use super::analyze::analyze_spatial_robustness_weighted;

    let curves = vec![make_spatial_curve(0.0), make_spatial_curve(2.0)];
    let config = SpatialRobustnessConfig::default();
    let weights = [0.25, 0.75];
    let result = analyze_spatial_robustness_weighted(&curves, &config, Some(&weights)).unwrap();
    assert_eq!(result.averaged_curve.freq.len(), curves[0].freq.len());
}

#[test]
fn analyze_spatial_robustness_with_bootstrap() {
    use super::analyze::analyze_spatial_robustness_with_bootstrap;
    use super::bootstrap_config::BootstrapConfig;

    let curves = vec![make_spatial_curve(0.0), make_spatial_curve(1.0), make_spatial_curve(-1.0)];
    let config = SpatialRobustnessConfig::default();
    let bootstrap = BootstrapConfig {
        num_resamples: 50,
        alpha: 0.10,
        seed: 1,
    };
    let result = analyze_spatial_robustness_with_bootstrap(&curves, &config, &bootstrap, None).unwrap();
    assert!(result.bootstrap.is_some());
}

// ---------------------------------------------------------------------------
// Tests for spatial_robustness/bootstrap_config.rs
// ---------------------------------------------------------------------------

#[test]
fn bootstrap_config_default_values() {
    use super::bootstrap_config::BootstrapConfig;

    let config = BootstrapConfig::default();
    assert_eq!(config.num_resamples, 500);
    assert!((config.alpha - 0.10).abs() < 1e-9);
    assert_eq!(config.seed, 0xC0FFEE);
}

// ---------------------------------------------------------------------------
// Tests for spatial_robustness/misc.rs
// ---------------------------------------------------------------------------

#[test]
fn percentile_sorted_edge_cases() {
    use super::misc::percentile_sorted;

    assert!(percentile_sorted(&[], 0.5).is_nan());
    assert_eq!(percentile_sorted(&[5.0], 0.5), 5.0);
    assert_eq!(percentile_sorted(&[1.0, 3.0], 0.0), 1.0);
    assert_eq!(percentile_sorted(&[1.0, 3.0], 1.0), 3.0);
    let mid = percentile_sorted(&[1.0, 3.0], 0.5);
    assert!((mid - 2.0).abs() < 1e-9);
    assert_eq!(percentile_sorted(&[1.0, 3.0], -1.0), 1.0);
    assert_eq!(percentile_sorted(&[1.0, 3.0], 2.0), 3.0);
}

#[test]
fn validate_spatial_curves_errors() {
    use super::misc::validate_spatial_curves;

    assert!(validate_spatial_curves(&[]).is_err());

    let bad = crate::Curve {
        freq: Array1::from_vec(vec![100.0, 50.0]),
        spl: Array1::from_vec(vec![80.0, 82.0]),
        phase: None,
        ..Default::default()
    };
    assert!(validate_spatial_curves(std::slice::from_ref(&bad)).is_err());

    let c1 = make_spatial_curve(0.0);
    let mut c2 = make_spatial_curve(1.0);
    c2.freq = Array1::from_vec(vec![100.0, 200.0, 400.0, 800.0, 2000.0]);
    assert!(validate_spatial_curves(&[c1, c2]).is_err());
}

#[test]
fn is_valid_spatial_frequency_grid_checks() {
    use super::misc::is_valid_spatial_frequency_grid;

    assert!(is_valid_spatial_frequency_grid(&Array1::from_vec(vec![100.0, 200.0, 400.0])));
    assert!(!is_valid_spatial_frequency_grid(&Array1::from_vec(vec![])));
    assert!(!is_valid_spatial_frequency_grid(&Array1::from_vec(vec![100.0, 50.0])));
    assert!(!is_valid_spatial_frequency_grid(&Array1::from_vec(vec![100.0, f64::NAN])));
    assert!(!is_valid_spatial_frequency_grid(&Array1::from_vec(vec![-100.0, 200.0])));
}

#[test]
fn normalized_weights_cases() {
    use super::misc::normalized_weights;

    let uniform = normalized_weights(4, None);
    assert_eq!(uniform, vec![0.25; 4]);

    let valid = normalized_weights(2, Some(&[1.0, 1.0]));
    assert_eq!(valid, vec![0.5, 0.5]);

    let wrong_len = normalized_weights(2, Some(&[1.0]));
    assert_eq!(wrong_len, vec![0.5, 0.5]);

    let non_finite = normalized_weights(2, Some(&[f64::NAN, 1.0]));
    assert_eq!(non_finite, vec![0.0, 1.0]);

    let zero_sum = normalized_weights(2, Some(&[0.0, 0.0]));
    assert_eq!(zero_sum, vec![0.5, 0.5]);
}

#[test]
fn test_correction_depth_with_smoothing_enabled() {
    // Test that smoothing doesn't produce NaN or out-of-range values
    let freq = Array1::from_vec(vec![50.0, 100.0, 200.0, 500.0, 1000.0]);
    let variance = Array1::from_vec(vec![1.0, 8.0, 1.0, 8.0, 1.0]);
    let config = SpatialRobustnessConfig {
        mask_smoothing_octaves: 0.5, // smoothing enabled
        ..Default::default()
    };

    let depth = correction_depth_mask(&freq, &variance, &config);
    for &d in depth.iter() {
        assert!(d.is_finite(), "depth should be finite");
        assert!(
            (0.0..=1.0).contains(&d),
            "depth should be in [0, 1], got {}",
            d
        );
    }
}
