[package]
name = "autoeq-fir"
version = "0.5.3"
edition = "2024"
description = "FIR filter design and serialization for AutoEQ"
license = "GPL-3.0-or-later"
documentation = "https://docs.rs/autoeq-fir"
homepage = "https://github.com/pierreaubert/autoeq"

[lints]
workspace = true

[dependencies]
autoeq-core = { workspace = true }
hound = { workspace = true }
math-iir-fir = { workspace = true }
ndarray = { workspace = true }
num-complex = { workspace = true }
rustfft = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
