[package]
name = "autoeq-fir"
version.workspace = true
edition = "2024"
description = "FIR filter design and serialization for AutoEQ"
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
autoeq-core = { workspace = true }
hound = { workspace = true }
math-iir-fir = { workspace = true }
ndarray = { workspace = true }
num-complex = { workspace = true }
rustfft = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
