// r2factor:facade — do not pass this file back into r2factor
// Auto-generated by r2factor. Manual edits will be overwritten on next split.

//! Spinorama measurement bundle and builder.
//!
//! [`SpinoramaBundle`] replaces the ad-hoc `read::Cea2034Data` struct. It groups
//! the standard CEA2034 curves together, computes the derived directivity
//! indices, and computes the Predicted In-Room (PIR) response from the LW/ER/SP
//! curves when it is not supplied explicitly.

use super::compute_pir_from_lw_er_sp;
use crate::Curve;
use crate::error::AutoeqError;
use std::collections::HashMap;

/// A complete CEA2034 / Spinorama measurement bundle.
#[derive(Debug, Clone)]
pub struct SpinoramaBundle {
    /// On Axis response
    pub on_axis: Curve,
    /// Listening Window response
    pub listening_window: Curve,
    /// Early Reflections response
    pub early_reflections: Curve,
    /// Sound Power response
    pub sound_power: Curve,
    /// Estimated In-Room Response (PIR)
    pub estimated_in_room: Curve,
    /// Early Reflections Directivity Index (On Axis - ER)
    pub er_di: Curve,
    /// Sound Power Directivity Index (On Axis - SP)
    pub sp_di: Curve,
    /// All curves as a HashMap (for backward compatibility with JSON/extraction code)
    pub curves: HashMap<String, Curve>,
}

impl SpinoramaBundle {
    /// Return the PIR curve, which is always derived from the spin data.
    pub fn pir(&self) -> &Curve {
        &self.estimated_in_room
    }
}

/// Fluent builder for [`SpinoramaBundle`].
///
/// Required curves can be supplied either by name through [`Self::curve`] (or
/// [`Self::curves`]) or set directly. On build, the builder validates that the
/// required curves are present, computes the directivity indices, and computes
/// the PIR response if it was not supplied explicitly.
#[derive(Debug, Clone, Default)]
pub struct SpinoramaBundleBuilder {
    on_axis: Option<Curve>,
    listening_window: Option<Curve>,
    early_reflections: Option<Curve>,
    sound_power: Option<Curve>,
    estimated_in_room: Option<Curve>,
    curves: HashMap<String, Curve>,
}

impl SpinoramaBundleBuilder {
    /// Create an empty builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a curve by name.
    ///
    /// Standard names (`On Axis`, `Listening Window`, `Early Reflections`,
    /// `Sound Power`, `Estimated In-Room Response`) are recognised during
    /// [`Self::build`].
    #[must_use]
    pub fn curve(mut self, name: impl Into<String>, curve: Curve) -> Self {
        self.curves.insert(name.into(), curve);
        self
    }

    /// Set the entire curve map.
    #[must_use]
    pub fn curves(mut self, curves: HashMap<String, Curve>) -> Self {
        self.curves = curves;
        self
    }

    /// Set the On Axis response directly.
    #[must_use]
    pub fn on_axis(mut self, curve: Curve) -> Self {
        self.on_axis = Some(curve);
        self
    }

    /// Set the Listening Window response directly.
    #[must_use]
    pub fn listening_window(mut self, curve: Curve) -> Self {
        self.listening_window = Some(curve);
        self
    }

    /// Set the Early Reflections response directly.
    #[must_use]
    pub fn early_reflections(mut self, curve: Curve) -> Self {
        self.early_reflections = Some(curve);
        self
    }

    /// Set the Sound Power response directly.
    #[must_use]
    pub fn sound_power(mut self, curve: Curve) -> Self {
        self.sound_power = Some(curve);
        self
    }

    /// Set the Estimated In-Room Response directly.
    ///
    /// When omitted, the builder computes it from LW/ER/SP using the standard
    /// CEA2034 weights.
    #[must_use]
    pub fn estimated_in_room(mut self, curve: Curve) -> Self {
        self.estimated_in_room = Some(curve);
        self
    }

    /// Consume the builder and return a validated [`SpinoramaBundle`].
    ///
    /// # Errors
    /// Returns `AutoeqError::InvalidConfiguration` if a required curve is
    /// missing or if the curves have inconsistent lengths.
    pub fn build(self) -> Result<SpinoramaBundle, AutoeqError> {
        let mut curves = self.curves;

        let take_or_lookup = |owned: Option<Curve>, name: &str, curves: &mut HashMap<String, Curve>| {
            owned
                .or_else(|| curves.remove(name))
                .ok_or_else(|| AutoeqError::InvalidConfiguration {
                    message: format!("Missing CEA2034 curve: {}", name),
                })
        };

        let on_axis = take_or_lookup(self.on_axis, "On Axis", &mut curves)?;
        let listening_window = take_or_lookup(self.listening_window, "Listening Window", &mut curves)?;
        let early_reflections = take_or_lookup(self.early_reflections, "Early Reflections", &mut curves)?;
        let sound_power = take_or_lookup(self.sound_power, "Sound Power", &mut curves)?;

        let estimated_in_room = match self.estimated_in_room {
            Some(c) => c,
            None => {
                let pir_spl = compute_pir_from_lw_er_sp(
                    &listening_window.spl,
                    &early_reflections.spl,
                    &sound_power.spl,
                );
                Curve {
                    freq: listening_window.freq.clone(),
                    spl: pir_spl,
                    phase: None,
                    ..Default::default()
                }
            }
        };

        let n = listening_window.freq.len();
        for (name, curve) in [
            ("On Axis", &on_axis),
            ("Listening Window", &listening_window),
            ("Early Reflections", &early_reflections),
            ("Sound Power", &sound_power),
        ] {
            if curve.freq.len() != n || curve.spl.len() != n {
                return Err(AutoeqError::InvalidConfiguration {
                    message: format!(
                        "CEA2034 curve '{}' length {} does not match listening window length {}",
                        name,
                        curve.spl.len(),
                        n
                    ),
                });
            }
        }

        let er_di = Curve {
            freq: on_axis.freq.clone(),
            spl: &on_axis.spl - &early_reflections.spl,
            phase: None,
            ..Default::default()
        };
        let sp_di = Curve {
            freq: on_axis.freq.clone(),
            spl: &on_axis.spl - &sound_power.spl,
            phase: None,
            ..Default::default()
        };

        curves.insert("On Axis".to_string(), on_axis.clone());
        curves.insert("Listening Window".to_string(), listening_window.clone());
        curves.insert("Early Reflections".to_string(), early_reflections.clone());
        curves.insert("Sound Power".to_string(), sound_power.clone());
        curves.insert("Estimated In-Room Response".to_string(), estimated_in_room.clone());

        Ok(SpinoramaBundle {
            on_axis,
            listening_window,
            early_reflections,
            sound_power,
            estimated_in_room,
            er_di,
            sp_di,
            curves,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::SpinoramaBundleBuilder;
    use crate::Curve;
    use ndarray::Array1;

    fn make_curve(spl: &[f64]) -> Curve {
        Curve {
            freq: Array1::from_vec(vec![100.0, 500.0, 1000.0]),
            spl: Array1::from_vec(spl.to_vec()),
            phase: None,
            ..Default::default()
        }
    }

    #[test]
    fn builder_computes_pir_and_indices() {
        let data = SpinoramaBundleBuilder::new()
            .curve("On Axis", make_curve(&[80.0, 82.0, 81.0]))
            .curve("Listening Window", make_curve(&[80.0, 82.0, 81.0]))
            .curve("Early Reflections", make_curve(&[78.0, 80.0, 79.0]))
            .curve("Sound Power", make_curve(&[77.0, 79.0, 78.0]))
            .build()
            .unwrap();

        assert_eq!(data.estimated_in_room.freq.len(), 3);
        assert_eq!(data.er_di.spl.len(), 3);
        assert_eq!(data.sp_di.spl.len(), 3);
        assert!(data.curves.contains_key("Estimated In-Room Response"));
    }

    #[test]
    fn builder_rejects_missing_curve() {
        let result = SpinoramaBundleBuilder::new()
            .curve("On Axis", make_curve(&[80.0, 82.0, 81.0]))
            .build();
        assert!(result.is_err());
    }
}
