//! Export DSP chain output to external audio processing formats
//!
//! Supports:
//! - CamillaDSP (YAML config)
//! - Equalizer APO / Peace GUI (text config)
//! - EasyEffects (JSON preset)
//! - Wavelet (GraphicEQ text)
//! - PipeWire filter-chain (SPA-JSON .conf)

use super::home_cinema::{BassManagementMatrix, BassManagementRoute, BassManagementRoutingGraph};
use super::types::{ChannelDspChain, DspChainOutput, PluginConfigWrapper};
use math_audio_iir_fir::Biquad;
use std::fmt::Write as FmtWrite;
use std::path::Path;

mod channel;
mod collect;
mod export_format;
mod extract;
mod misc;
mod package;
mod pipewire;
#[cfg(test)]
mod tests;
mod types;
mod write;

pub use export_format::*;
pub use package::*;

use channel::channel_short_name;
use channel::sorted_channels;
use collect::collect_all_plugins;
use collect::collect_camilladsp_filter_names;
use export_format::ensure_external_export_supported;
use extract::extract_convolution_paths;
use extract::extract_delay_ms;
use extract::extract_eq_filters;
use extract::extract_gain_db;
use misc::WAVELET_BANDS;
use misc::apo_filter_type;
use misc::easyeffects_filter_type;
use misc::parse_biquad_filter_type;
use misc::roon_filter_type;
use pipewire::pipewire_channel_position;
use pipewire::pipewire_filter_label;
use write::write_camilladsp_crossover_filter;
use write::write_camilladsp_delay_filter;
use write::write_camilladsp_filters_for_plugins;
use write::write_camilladsp_pipeline_filter_step;

/// Export a DSP chain output to the specified format
pub fn export_dsp_chain(
    output: &DspChainOutput,
    format: ExportFormat,
    path: &Path,
    sample_rate: f64,
) -> anyhow::Result<()> {
    ensure_external_export_supported(output, format)?;
    let content = match format {
        ExportFormat::CamillaDsp => export_camilladsp(output, sample_rate)?,
        ExportFormat::EqualizerApo => export_equalizer_apo(output)?,
        ExportFormat::EasyEffects => export_easyeffects(output)?,
        ExportFormat::Wavelet => export_wavelet(output, sample_rate)?,
        ExportFormat::PipeWire => export_pipewire(output, sample_rate)?,
        ExportFormat::RoonDsp => export_roon(output)?,
    };
    std::fs::write(path, content)?;
    Ok(())
}

/// Export a DSP chain and package convolution WAV sidecars beside the export
/// when the target format keeps `ir_file` references.
pub fn export_dsp_chain_with_convolution_sidecars(
    output: &DspChainOutput,
    format: ExportFormat,
    path: &Path,
    sample_rate: f64,
    source_dir: &Path,
) -> anyhow::Result<()> {
    let export_output = if export_format_preserves_convolution_paths(format) {
        let dest_dir = path.parent().unwrap_or_else(|| Path::new("."));
        package_convolution_sidecars(output, source_dir, dest_dir)?
    } else {
        output.clone()
    };
    export_dsp_chain(&export_output, format, path, sample_rate)
}

fn export_format_preserves_convolution_paths(format: ExportFormat) -> bool {
    matches!(
        format,
        ExportFormat::CamillaDsp | ExportFormat::EqualizerApo | ExportFormat::RoonDsp
    )
}

fn export_camilladsp(output: &DspChainOutput, sample_rate: f64) -> anyhow::Result<String> {
    if let Some(graph) = camilladsp_routing_graph(output) {
        if !graph.routes.is_empty() {
            return export_camilladsp_routed(output, &graph, sample_rate);
        }
    }

    let mut out = String::new();
    writeln!(out, "# CamillaDSP configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out)?;

    let channels = sorted_channels(output);
    let num_channels = channels.len();

    // Devices section
    writeln!(out, "devices:")?;
    writeln!(out, "  samplerate: {}", sample_rate as u32)?;
    writeln!(out, "  chunksize: 4096")?;
    writeln!(out, "  capture:")?;
    writeln!(out, "    type: File")?;
    writeln!(out, "    channels: {num_channels}")?;
    writeln!(out, "    filename: /dev/stdin")?;
    writeln!(out, "    format: S32LE")?;
    writeln!(out, "  playback:")?;
    writeln!(out, "    type: File")?;
    writeln!(out, "    channels: {num_channels}")?;
    writeln!(out, "    filename: /dev/stdout")?;
    writeln!(out, "    format: S32LE")?;
    writeln!(out)?;

    // Filters section
    writeln!(out, "filters:")?;

    for (ch_name, chain) in &channels {
        let prefix = ch_name.replace(' ', "_");
        write_camilladsp_filters_for_plugins(&mut out, &prefix, &chain.plugins, "")?;

        if let Some(drivers) = &chain.drivers {
            for driver in drivers {
                let driver_prefix = format!("{}_{}", prefix, driver.name.replace(' ', "_"));
                write_camilladsp_filters_for_plugins(
                    &mut out,
                    &driver_prefix,
                    &driver.plugins,
                    "",
                )?;
            }
        }
    }
    writeln!(out)?;

    // Pipeline section
    writeln!(out, "pipeline:")?;

    for (i, (ch_name, chain)) in channels.iter().enumerate() {
        let prefix = ch_name.replace(' ', "_");

        // Driver-level filters first
        if let Some(drivers) = &chain.drivers {
            writeln!(out, "# Channel: {} (drivers)", ch_name)?;
            for driver in drivers {
                let driver_prefix = format!("{}_{}", prefix, driver.name.replace(' ', "_"));
                let filter_names =
                    collect_camilladsp_filter_names(&driver_prefix, &driver.plugins, "");
                if !filter_names.is_empty() {
                    write_camilladsp_pipeline_filter_step(&mut out, i, &filter_names)?;
                }
            }
        }

        // Channel-level filters
        let filter_names = collect_camilladsp_filter_names(&prefix, &chain.plugins, "");
        if !filter_names.is_empty() {
            write_camilladsp_pipeline_filter_step(&mut out, i, &filter_names)?;
        }
    }

    Ok(out)
}

fn export_camilladsp_routed(
    output: &DspChainOutput,
    graph: &BassManagementRoutingGraph,
    sample_rate: f64,
) -> anyhow::Result<String> {
    let mut out = String::new();
    writeln!(out, "# CamillaDSP configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out, "# Routed bass-management graph export")?;
    writeln!(out)?;

    let input_channels = if graph.input_channels.is_empty() {
        sorted_channels(output)
            .into_iter()
            .map(|(name, _)| name.clone())
            .collect()
    } else {
        graph.input_channels.clone()
    };
    let output_channels = if graph.output_channels.is_empty() {
        input_channels.clone()
    } else {
        graph.output_channels.clone()
    };

    writeln!(out, "devices:")?;
    writeln!(out, "  samplerate: {}", sample_rate as u32)?;
    writeln!(out, "  chunksize: 4096")?;
    writeln!(out, "  capture:")?;
    writeln!(out, "    type: File")?;
    writeln!(out, "    channels: {}", input_channels.len())?;
    writeln!(out, "    filename: /dev/stdin")?;
    writeln!(out, "    format: S32LE")?;
    writeln!(out, "  playback:")?;
    writeln!(out, "    type: File")?;
    writeln!(out, "    channels: {}", output_channels.len())?;
    writeln!(out, "    filename: /dev/stdout")?;
    writeln!(out, "    format: S32LE")?;
    writeln!(out)?;

    writeln!(out, "filters:")?;
    for channel_name in &input_channels {
        if let Some(chain) = output.channels.get(channel_name) {
            let prefix = format!("pre_{}", camilladsp_name(channel_name));
            let plugins = plugins_for_stage(chain, "pre_route");
            write_camilladsp_filters_for_plugins(&mut out, &prefix, &plugins, "")?;
        }
    }

    for (route_idx, route) in graph.routes.iter().enumerate() {
        let prefix = camilladsp_route_prefix(route_idx, route);
        if let Some(freq) = route.high_pass_hz.or(route.low_pass_hz) {
            let output = if route.high_pass_hz.is_some() {
                "high"
            } else {
                "low"
            };
            write_camilladsp_crossover_filter(
                &mut out,
                &format!("{prefix}_crossover"),
                &route.crossover_type,
                freq,
                output,
            )?;
        }
        if route.delay_ms.abs() > 0.001 {
            write_camilladsp_delay_filter(&mut out, &format!("{prefix}_delay"), route.delay_ms)?;
        }
    }

    for channel_name in &output_channels {
        if let Some(chain) = output.channels.get(channel_name) {
            let prefix = format!("post_{}", camilladsp_name(channel_name));
            let plugins = plugins_for_stage(chain, "post_route");
            write_camilladsp_filters_for_plugins(&mut out, &prefix, &plugins, "")?;
        }
    }
    writeln!(out)?;

    writeln!(out, "mixers:")?;
    write_camilladsp_route_expand_mixer(&mut out, graph, input_channels.len())?;
    write_camilladsp_route_sum_mixer(&mut out, graph, output_channels.len())?;
    writeln!(out)?;

    writeln!(out, "pipeline:")?;
    for (input_idx, channel_name) in input_channels.iter().enumerate() {
        if let Some(chain) = output.channels.get(channel_name) {
            let prefix = format!("pre_{}", camilladsp_name(channel_name));
            let plugins = plugins_for_stage(chain, "pre_route");
            let filter_names = collect_camilladsp_filter_names(&prefix, &plugins, "");
            if !filter_names.is_empty() {
                write_camilladsp_pipeline_filter_step(&mut out, input_idx, &filter_names)?;
            }
        }
    }
    write_camilladsp_pipeline_mixer_step(&mut out, "roomeq_route_matrix")?;

    for (route_idx, route) in graph.routes.iter().enumerate() {
        let prefix = camilladsp_route_prefix(route_idx, route);
        let mut filter_names = Vec::new();
        if route.high_pass_hz.or(route.low_pass_hz).is_some() {
            filter_names.push(format!("{prefix}_crossover"));
        }
        if route.delay_ms.abs() > 0.001 {
            filter_names.push(format!("{prefix}_delay"));
        }
        if !filter_names.is_empty() {
            write_camilladsp_pipeline_filter_step(&mut out, route_idx, &filter_names)?;
        }
    }

    write_camilladsp_pipeline_mixer_step(&mut out, "roomeq_route_sum")?;
    for (output_idx, channel_name) in output_channels.iter().enumerate() {
        if let Some(chain) = output.channels.get(channel_name) {
            let prefix = format!("post_{}", camilladsp_name(channel_name));
            let plugins = plugins_for_stage(chain, "post_route");
            let filter_names = collect_camilladsp_filter_names(&prefix, &plugins, "");
            if !filter_names.is_empty() {
                write_camilladsp_pipeline_filter_step(&mut out, output_idx, &filter_names)?;
            }
        }
    }

    Ok(out)
}

fn camilladsp_routing_graph(output: &DspChainOutput) -> Option<BassManagementRoutingGraph> {
    output
        .metadata
        .as_ref()
        .and_then(|metadata| metadata.bass_management.as_ref())
        .and_then(|report| report.routing_graph.clone())
        .or_else(|| {
            output.global_plugins.iter().find_map(|plugin| {
                if plugin.plugin_type != "matrix"
                    || plugin
                        .parameters
                        .get("label")
                        .and_then(|label| label.as_str())
                        != Some("home_cinema_bass_management")
                {
                    return None;
                }
                let metadata = plugin.parameters.get("metadata")?;
                let routes: Vec<BassManagementRoute> =
                    serde_json::from_value(metadata.get("routes")?.clone()).ok()?;
                let matrix = Some(BassManagementMatrix {
                    input_channel_map: serde_json::from_value(
                        plugin.parameters.get("input_channel_map")?.clone(),
                    )
                    .ok()?,
                    output_channel_map: serde_json::from_value(
                        plugin.parameters.get("output_channel_map")?.clone(),
                    )
                    .ok()?,
                    matrix: serde_json::from_value(plugin.parameters.get("matrix")?.clone())
                        .ok()?,
                    route_count: routes.len(),
                });
                let input_channels = ordered_route_channels(
                    &routes,
                    |route| route.source_index,
                    |route| &route.source_channel,
                );
                let output_channels = ordered_route_channels(
                    &routes,
                    |route| route.destination_index,
                    |route| &route.destination,
                );
                Some(BassManagementRoutingGraph {
                    physical_sub_output: metadata
                        .get("physical_sub_output")
                        .and_then(|value| value.as_str())
                        .unwrap_or("")
                        .to_string(),
                    input_channels,
                    output_channels,
                    routes,
                    matrix,
                    advisories: serde_json::from_value(
                        metadata
                            .get("advisories")
                            .cloned()
                            .unwrap_or_else(|| serde_json::json!([])),
                    )
                    .unwrap_or_default(),
                })
            })
        })
}

fn ordered_route_channels<'a, F, G>(
    routes: &'a [BassManagementRoute],
    index: F,
    name: G,
) -> Vec<String>
where
    F: Fn(&'a BassManagementRoute) -> usize,
    G: Fn(&'a BassManagementRoute) -> &'a String,
{
    let mut indexed: Vec<(usize, String)> = routes
        .iter()
        .map(|route| (index(route), name(route).clone()))
        .collect();
    indexed.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));
    indexed.dedup_by(|a, b| a.0 == b.0 && a.1 == b.1);
    indexed.into_iter().map(|(_, name)| name).collect()
}

fn plugins_for_stage(chain: &ChannelDspChain, stage: &str) -> Vec<PluginConfigWrapper> {
    chain
        .plugins
        .iter()
        .filter(|plugin| {
            plugin
                .parameters
                .get("room_eq_stage")
                .and_then(|value| value.as_str())
                == Some(stage)
        })
        .cloned()
        .collect()
}

fn camilladsp_name(name: &str) -> String {
    name.chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn camilladsp_route_prefix(route_idx: usize, route: &BassManagementRoute) -> String {
    format!(
        "route_{route_idx}_{}_to_{}",
        camilladsp_name(&route.source_channel),
        camilladsp_name(&route.destination)
    )
}

fn write_camilladsp_route_expand_mixer(
    out: &mut String,
    graph: &BassManagementRoutingGraph,
    input_channels: usize,
) -> anyhow::Result<()> {
    writeln!(out, "  roomeq_route_matrix:")?;
    writeln!(out, "    channels:")?;
    writeln!(out, "      in: {input_channels}")?;
    writeln!(out, "      out: {}", graph.routes.len())?;
    writeln!(out, "    mapping:")?;
    for (route_idx, route) in graph.routes.iter().enumerate() {
        writeln!(out, "    - dest: {route_idx}")?;
        writeln!(out, "      mute: false")?;
        writeln!(out, "      sources:")?;
        writeln!(out, "      - channel: {}", route.source_index)?;
        writeln!(out, "        gain: {:.6}", route.gain_db)?;
        writeln!(out, "        inverted: {}", route.polarity_inverted)?;
        writeln!(out, "        mute: false")?;
        writeln!(out, "        scale: dB")?;
    }
    Ok(())
}

fn write_camilladsp_route_sum_mixer(
    out: &mut String,
    graph: &BassManagementRoutingGraph,
    output_channels: usize,
) -> anyhow::Result<()> {
    writeln!(out, "  roomeq_route_sum:")?;
    writeln!(out, "    channels:")?;
    writeln!(out, "      in: {}", graph.routes.len())?;
    writeln!(out, "      out: {output_channels}")?;
    writeln!(out, "    mapping:")?;
    for dest_idx in 0..output_channels {
        writeln!(out, "    - dest: {dest_idx}")?;
        writeln!(out, "      mute: false")?;
        writeln!(out, "      sources:")?;
        for (route_idx, route) in graph.routes.iter().enumerate() {
            if route.destination_index == dest_idx {
                writeln!(out, "      - channel: {route_idx}")?;
                writeln!(out, "        gain: 0")?;
                writeln!(out, "        inverted: false")?;
                writeln!(out, "        mute: false")?;
                writeln!(out, "        scale: dB")?;
            }
        }
    }
    Ok(())
}

fn write_camilladsp_pipeline_mixer_step(out: &mut String, name: &str) -> anyhow::Result<()> {
    writeln!(out, "- bypassed: null")?;
    writeln!(out, "  name: {name}")?;
    writeln!(out, "  type: Mixer")?;
    Ok(())
}

fn export_equalizer_apo(output: &DspChainOutput) -> anyhow::Result<String> {
    let mut out = String::new();
    writeln!(out, "# Equalizer APO configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out)?;

    let channels = sorted_channels(output);

    for (ch_name, chain) in &channels {
        let short = channel_short_name(ch_name);
        writeln!(out, "Channel: {short}")?;

        // Collect all plugins from channel + drivers
        let plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();

        // Gain (preamp)
        let gain = extract_gain_db(&plugins);
        if gain.abs() > 0.01 {
            writeln!(out, "Preamp: {gain:+.1} dB")?;
        }

        // Delay
        if let Some(delay) = extract_delay_ms(&plugins) {
            writeln!(out, "Delay: {delay:.3} ms")?;
        }

        // EQ filters
        let filters = extract_eq_filters(&plugins);
        for (i, f) in filters.iter().enumerate() {
            let ft = apo_filter_type(&f.filter_type);
            match f.filter_type.as_str() {
                "lowpass" | "highpass" | "highpassvariableq" => {
                    writeln!(out, "Filter {:2}: ON {ft} Fc {:.0} Hz", i + 1, f.freq)?;
                }
                _ => {
                    writeln!(
                        out,
                        "Filter {:2}: ON {ft} Fc {:.0} Hz Gain {:+.2} dB Q {:.4}",
                        i + 1,
                        f.freq,
                        f.gain_db,
                        f.q
                    )?;
                }
            }
        }

        // Convolution
        let conv_paths = extract_convolution_paths(&plugins);
        for path in &conv_paths {
            writeln!(out, "Convolution: {path}")?;
        }

        writeln!(out)?;
    }

    Ok(out)
}

fn export_easyeffects(output: &DspChainOutput) -> anyhow::Result<String> {
    let channels = sorted_channels(output);

    // Merge all channel EQ filters into one preset (EasyEffects applies globally)
    let mut all_filters = Vec::new();
    let mut min_gain = 0.0f64;

    // Check for convolution/FIR and warn
    let mut has_unsupported = false;

    for (ch_name, chain) in &channels {
        let plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();
        let filters = extract_eq_filters(&plugins);
        let gain = extract_gain_db(&plugins);

        if !extract_convolution_paths(&plugins).is_empty() {
            has_unsupported = true;
            log::warn!(
                "EasyEffects: skipping convolution for channel '{}' (not supported)",
                ch_name
            );
        }

        // Use most negative gain as preamp to prevent clipping
        if gain < min_gain {
            min_gain = gain;
        }

        all_filters.extend(filters);
    }

    if has_unsupported {
        log::warn!("EasyEffects does not support FIR convolution filters; they were skipped");
    }

    // Build JSON preset
    let mut bands = serde_json::Map::new();
    for (i, f) in all_filters.iter().enumerate().take(30) {
        let band_key = format!("band{i}");
        let mut band = serde_json::Map::new();
        band.insert("frequency".to_string(), serde_json::json!(f.freq));
        band.insert("gain".to_string(), serde_json::json!(f.gain_db));
        band.insert("q".to_string(), serde_json::json!(f.q));
        band.insert(
            "type".to_string(),
            serde_json::json!(easyeffects_filter_type(&f.filter_type)),
        );
        band.insert("mode".to_string(), serde_json::json!("RLC (BT)"));
        band.insert("slope".to_string(), serde_json::json!("x1"));
        band.insert("solo".to_string(), serde_json::json!(false));
        band.insert("mute".to_string(), serde_json::json!(false));
        bands.insert(band_key, serde_json::Value::Object(band));
    }

    let preset = serde_json::json!({
        "output": {
            "equalizer#0": {
                "input-gain": min_gain,
                "output-gain": 0.0,
                "num-bands": all_filters.len().min(30),
                "split-channels": false,
                "left": bands,
                "right": bands,
            }
        }
    });

    Ok(serde_json::to_string_pretty(&preset)?)
}

fn export_wavelet(output: &DspChainOutput, sample_rate: f64) -> anyhow::Result<String> {
    let channels = sorted_channels(output);

    let mut has_unsupported = false;

    // Average the response across all channels
    let mut band_gains = [0.0f64; 9];
    let mut n_channels = 0;

    for (ch_name, chain) in &channels {
        let plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();
        let filters = extract_eq_filters(&plugins);
        let gain = extract_gain_db(&plugins);

        if !extract_convolution_paths(&plugins).is_empty() {
            has_unsupported = true;
            log::warn!(
                "Wavelet: skipping convolution for channel '{}' (not supported)",
                ch_name
            );
        }

        // Build Biquad chain and evaluate at each band frequency
        let biquads: Vec<Biquad> = filters
            .iter()
            .map(|f| {
                let ft = parse_biquad_filter_type(&f.filter_type)?;
                Ok(Biquad::new(ft, f.freq, sample_rate, f.q, f.gain_db))
            })
            .collect::<anyhow::Result<_>>()?;

        for (i, &freq) in WAVELET_BANDS.iter().enumerate() {
            let mut db = gain;
            for bq in &biquads {
                db += bq.log_result(freq);
            }
            band_gains[i] += db;
        }
        n_channels += 1;
    }

    if has_unsupported {
        log::warn!("Wavelet does not support FIR convolution filters; they were skipped");
    }

    // Average across channels
    if n_channels > 1 {
        for g in &mut band_gains {
            *g /= n_channels as f64;
        }
    }

    // Format output
    let mut out = String::new();
    writeln!(out, "# Wavelet GraphicEQ")?;
    writeln!(out, "# Generated by roomeq")?;
    write!(out, "GraphicEQ:")?;
    for (i, (&freq, &gain)) in WAVELET_BANDS.iter().zip(band_gains.iter()).enumerate() {
        if i > 0 {
            write!(out, ";")?;
        }
        write!(out, " {:.0} {:.1}", freq, gain)?;
    }
    writeln!(out)?;

    Ok(out)
}

fn export_pipewire(output: &DspChainOutput, sample_rate: f64) -> anyhow::Result<String> {
    let mut out = String::new();
    writeln!(out, "# PipeWire filter-chain configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out)?;
    writeln!(out, "context.modules = [")?;
    writeln!(out, "  {{ name = libpipewire-module-filter-chain")?;
    writeln!(out, "    args = {{")?;

    let channels = sorted_channels(output);
    let num_channels = channels.len();

    // Build channel position list
    let positions: Vec<&str> = channels
        .iter()
        .map(|(name, _)| channel_short_name(name))
        .collect();
    let positions_str = positions
        .iter()
        .map(|p| format!("\"{}\"", pipewire_channel_position(p)))
        .collect::<Vec<_>>()
        .join(", ");

    // Nodes
    writeln!(out, "      filter.graph = {{")?;
    writeln!(out, "        nodes = [")?;

    let mut all_node_names: Vec<Vec<String>> = Vec::new(); // per-channel node names

    for (ch_idx, (ch_name, chain)) in channels.iter().enumerate() {
        let ch_prefix = format!("ch{}_{}", ch_idx, ch_name.replace(' ', "_"));
        let mut node_names = Vec::new();

        // Collect all plugins
        let all_plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();

        // Gain node
        let gain = extract_gain_db(&all_plugins);
        if gain.abs() > 0.01 {
            let node_name = format!("{ch_prefix}_gain");
            writeln!(
                out,
                "          {{ type = builtin  name = \"{node_name}\"  label = bq_highshelf  control = {{ \"Freq\" = 0  \"Q\" = 1.0  \"Gain\" = {gain:.2} }} }}"
            )?;
            node_names.push(node_name);
        }

        // Delay node (PipeWire uses delay builtin)
        if let Some(delay_ms) = extract_delay_ms(&all_plugins) {
            let delay_samples = (delay_ms / 1000.0 * sample_rate).round() as u64;
            let node_name = format!("{ch_prefix}_delay");
            writeln!(
                out,
                "          {{ type = builtin  name = \"{node_name}\"  label = delay  control = {{ \"Delay\" = {delay_samples} }} }}"
            )?;
            node_names.push(node_name);
        }

        // EQ filter nodes
        let filters = extract_eq_filters(&all_plugins);
        for (i, f) in filters.iter().enumerate() {
            let label = pipewire_filter_label(&f.filter_type)?;
            let node_name = format!("{ch_prefix}_eq_{i}");
            match f.filter_type.as_str() {
                "lowpass" | "highpass" | "highpassvariableq" => {
                    writeln!(
                        out,
                        "          {{ type = builtin  name = \"{node_name}\"  label = {label}  control = {{ \"Freq\" = {:.1}  \"Q\" = {:.4} }} }}",
                        f.freq, f.q
                    )?;
                }
                _ => {
                    writeln!(
                        out,
                        "          {{ type = builtin  name = \"{node_name}\"  label = {label}  control = {{ \"Freq\" = {:.1}  \"Q\" = {:.4}  \"Gain\" = {:.2} }} }}",
                        f.freq, f.q, f.gain_db
                    )?;
                }
            }
            node_names.push(node_name);
        }

        all_node_names.push(node_names);
    }

    writeln!(out, "        ]")?;

    // Links: chain nodes sequentially per channel
    writeln!(out, "        links = [")?;
    for nodes in &all_node_names {
        for pair in nodes.windows(2) {
            writeln!(
                out,
                "          {{ output = \"{}:Out\"  input = \"{}:In\" }}",
                pair[0], pair[1]
            )?;
        }
    }
    writeln!(out, "        ]")?;

    // Inputs/outputs
    writeln!(out, "        inputs  = [")?;
    for (ch_idx, nodes) in all_node_names.iter().enumerate() {
        if let Some(first) = nodes.first() {
            writeln!(out, "          {{ node = \"{first}\"  port = \"In\" }}")?;
        } else {
            // No processing nodes — passthrough
            writeln!(out, "          {{ }}")?;
        }
        let _ = ch_idx; // suppress warning
    }
    writeln!(out, "        ]")?;

    writeln!(out, "        outputs = [")?;
    for nodes in &all_node_names {
        if let Some(last) = nodes.last() {
            writeln!(out, "          {{ node = \"{last}\"  port = \"Out\" }}")?;
        } else {
            writeln!(out, "          {{ }}")?;
        }
    }
    writeln!(out, "        ]")?;

    writeln!(out, "      }}")?; // filter.graph

    // Capture/playback props
    writeln!(out, "      capture.props = {{")?;
    writeln!(out, "        audio.channels = {num_channels}")?;
    writeln!(out, "        audio.position = [ {positions_str} ]")?;
    writeln!(out, "      }}")?;
    writeln!(out, "      playback.props = {{")?;
    writeln!(out, "        audio.channels = {num_channels}")?;
    writeln!(out, "        audio.position = [ {positions_str} ]")?;
    writeln!(out, "      }}")?;

    writeln!(out, "    }}")?; // args
    writeln!(out, "  }}")?; // module
    writeln!(out, "]")?;

    Ok(out)
}

/// Export a DSP chain as a Roon DSP Engine preset.
///
/// Roon's DSP Engine supports per-channel parametric EQ (up to 20 bands),
/// headroom management (preamp gain), and convolution (WAV files).
/// The output is a JSON object with per-channel sections that can be
/// referenced when configuring Roon's DSP Engine manually.
fn export_roon(output: &DspChainOutput) -> anyhow::Result<String> {
    let channels = sorted_channels(output);

    let mut roon = serde_json::Map::new();
    roon.insert(
        "_comment".to_string(),
        serde_json::json!("Roon DSP Engine preset — generated by roomeq"),
    );

    let mut channel_configs = serde_json::Map::new();

    for (ch_name, chain) in &channels {
        let all_plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();

        let mut ch = serde_json::Map::new();

        // Headroom / preamp gain
        let gain = extract_gain_db(&all_plugins);
        if gain.abs() > 0.01 {
            ch.insert("headroom_gain_db".to_string(), serde_json::json!(gain));
        }

        // Delay (Roon doesn't have a per-channel delay in PEQ, but we include it
        // so the user knows what value to set in Speaker Setup > Distance)
        if let Some(delay_ms) = extract_delay_ms(&all_plugins) {
            ch.insert("delay_ms".to_string(), serde_json::json!(delay_ms));
        }

        // Parametric EQ bands (max 20 per Roon endpoint)
        let filters = extract_eq_filters(&all_plugins);
        let mut bands = Vec::new();
        for f in filters.iter().take(20) {
            let mut band = serde_json::Map::new();
            band.insert(
                "type".to_string(),
                serde_json::json!(roon_filter_type(&f.filter_type)),
            );
            band.insert("frequency".to_string(), serde_json::json!(f.freq));
            band.insert("gain".to_string(), serde_json::json!(f.gain_db));
            band.insert("q".to_string(), serde_json::json!(f.q));
            band.insert("enabled".to_string(), serde_json::json!(true));
            bands.push(serde_json::Value::Object(band));
        }
        if !bands.is_empty() {
            ch.insert(
                "parametric_eq".to_string(),
                serde_json::json!({
                    "bands": bands,
                    "is_enabled": true
                }),
            );
        }

        // Convolution IR files
        let conv_paths = extract_convolution_paths(&all_plugins);
        if !conv_paths.is_empty() {
            ch.insert(
                "convolution".to_string(),
                serde_json::json!({
                    "ir_files": conv_paths,
                    "is_enabled": true
                }),
            );
        }

        channel_configs.insert(ch_name.to_string(), serde_json::Value::Object(ch));
    }

    roon.insert(
        "channels".to_string(),
        serde_json::Value::Object(channel_configs),
    );

    Ok(serde_json::to_string_pretty(&serde_json::Value::Object(
        roon,
    ))?)
}
