//! Export DSP chain output to external audio processing formats
//!
//! Supports:
//! - CamillaDSP (YAML config)
//! - Equalizer APO / Peace GUI (text config)
//! - EasyEffects (JSON preset)
//! - Wavelet (GraphicEQ text)
//! - PipeWire filter-chain (SPA-JSON .conf)

use super::home_cinema::{BassManagementMatrix, BassManagementRoute, BassManagementRoutingGraph};
use super::types::{ChannelDspChain, DspChainOutput, PluginConfigWrapper};
use math_audio_iir_fir::Biquad;
use std::fmt::Write as FmtWrite;
use std::path::Path;

mod channel;
mod collect;
mod conformance;
mod export_format;
mod extract;
mod misc;
mod package;
mod pipewire;
#[cfg(test)]
mod tests;
mod types;
mod write;

pub use export_format::*;
pub use package::*;

use channel::channel_short_name;
use channel::sorted_channels;
use collect::collect_all_plugins;
use conformance::ExportArtifactManifest;
use conformance::ExportNodeKind;
use conformance::normalize_export_identifier;
use conformance::routed_channel_names;
use conformance::validate_camilladsp_input;
use export_format::ensure_external_export_supported;
use extract::extract_convolution_paths;
use extract::extract_delay_ms;
use extract::extract_eq_filters;
use extract::extract_gain_db;
use misc::WAVELET_BANDS;
use misc::apo_filter_type;
use misc::easyeffects_filter_type;
use misc::parse_biquad_filter_type;
use misc::roon_filter_type;
use pipewire::pipewire_channel_position;
use pipewire::pipewire_filter_label;
use write::write_camilladsp_crossover_filter;
use write::write_camilladsp_delay_filter;
use write::write_camilladsp_filters_for_plugins;
use write::write_camilladsp_pipeline_filter_step;

/// Export a DSP chain output to the specified format
pub fn export_dsp_chain(
    output: &DspChainOutput,
    format: ExportFormat,
    path: &Path,
    sample_rate: f64,
) -> anyhow::Result<()> {
    let content = render_dsp_chain(output, format, sample_rate)?;
    std::fs::write(path, content)?;
    Ok(())
}

/// Render an external export after applying the backend's conformance checks.
/// Keeping rendering independent from filesystem output gives every exporter a
/// shared seam for structural and backend-native validation tests.
fn render_dsp_chain(
    output: &DspChainOutput,
    format: ExportFormat,
    sample_rate: f64,
) -> anyhow::Result<String> {
    ensure_external_export_supported(output, format)?;
    match format {
        ExportFormat::CamillaDsp => export_camilladsp(output, sample_rate),
        ExportFormat::EqualizerApo => export_equalizer_apo(output),
        ExportFormat::EasyEffects => export_easyeffects(output),
        ExportFormat::Wavelet => export_wavelet(output, sample_rate),
        ExportFormat::PipeWire => export_pipewire(output, sample_rate),
        ExportFormat::RoonDsp => export_roon(output),
    }
}

/// Export a DSP chain and package convolution WAV sidecars beside the export
/// when the target format keeps `ir_file` references.
pub fn export_dsp_chain_with_convolution_sidecars(
    output: &DspChainOutput,
    format: ExportFormat,
    path: &Path,
    sample_rate: f64,
    source_dir: &Path,
) -> anyhow::Result<()> {
    let export_output = if export_format_preserves_convolution_paths(format) {
        let dest_dir = path.parent().unwrap_or_else(|| Path::new("."));
        package_convolution_sidecars(output, source_dir, dest_dir)?
    } else {
        output.clone()
    };
    export_dsp_chain(&export_output, format, path, sample_rate)
}

fn export_format_preserves_convolution_paths(format: ExportFormat) -> bool {
    matches!(
        format,
        ExportFormat::CamillaDsp | ExportFormat::EqualizerApo | ExportFormat::RoonDsp
    )
}

fn export_camilladsp(output: &DspChainOutput, sample_rate: f64) -> anyhow::Result<String> {
    validate_camilladsp_input(output, Some(sample_rate))?;
    if let Some(graph) = camilladsp_routing_graph(output)
        && !graph.routes.is_empty()
    {
        return export_camilladsp_routed(output, &graph, sample_rate);
    }

    let mut out = String::new();
    let mut manifest = ExportArtifactManifest::new(ExportFormat::CamillaDsp);
    writeln!(out, "# CamillaDSP configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out)?;

    let channels = sorted_channels(output);
    let num_channels = channels.len();

    // Devices section
    writeln!(out, "devices:")?;
    writeln!(out, "  samplerate: {}", sample_rate as u32)?;
    writeln!(out, "  chunksize: 4096")?;
    writeln!(out, "  capture:")?;
    writeln!(out, "    type: Stdin")?;
    writeln!(out, "    channels: {num_channels}")?;
    writeln!(out, "    format: S32_LE")?;
    writeln!(out, "  playback:")?;
    writeln!(out, "    type: Stdout")?;
    writeln!(out, "    channels: {num_channels}")?;
    writeln!(out, "    format: S32_LE")?;
    writeln!(out)?;

    // Filters section
    writeln!(out, "filters:")?;

    let mut channel_filter_names = Vec::with_capacity(channels.len());
    for (ch_name, chain) in &channels {
        let prefix = normalize_export_identifier(ch_name);
        let filter_names =
            write_camilladsp_filters_for_plugins(&mut out, &mut manifest, &prefix, &chain.plugins)?;
        channel_filter_names.push(filter_names);
    }
    writeln!(out)?;

    // Pipeline section
    writeln!(out, "pipeline:")?;

    for (i, ((ch_name, _), filter_names)) in
        channels.iter().zip(channel_filter_names.iter()).enumerate()
    {
        if !filter_names.is_empty() {
            write_camilladsp_pipeline_filter_step(
                &mut out,
                &mut manifest,
                i,
                num_channels,
                filter_names,
                &format!("channel '{ch_name}' pipeline"),
            )?;
        }
    }

    manifest.validate()?;
    Ok(out)
}

fn export_camilladsp_routed(
    output: &DspChainOutput,
    graph: &BassManagementRoutingGraph,
    sample_rate: f64,
) -> anyhow::Result<String> {
    let mut out = String::new();
    let mut manifest = ExportArtifactManifest::new(ExportFormat::CamillaDsp);
    writeln!(out, "# CamillaDSP configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out, "# Routed bass-management graph export")?;
    writeln!(out)?;

    let (input_channels, output_channels) = routed_channel_names(output, graph);

    writeln!(out, "devices:")?;
    writeln!(out, "  samplerate: {}", sample_rate as u32)?;
    writeln!(out, "  chunksize: 4096")?;
    writeln!(out, "  capture:")?;
    writeln!(out, "    type: Stdin")?;
    writeln!(out, "    channels: {}", input_channels.len())?;
    writeln!(out, "    format: S32_LE")?;
    writeln!(out, "  playback:")?;
    writeln!(out, "    type: Stdout")?;
    writeln!(out, "    channels: {}", output_channels.len())?;
    writeln!(out, "    format: S32_LE")?;
    writeln!(out)?;

    writeln!(out, "filters:")?;
    let mut pre_route_filter_names = Vec::with_capacity(input_channels.len());
    for channel_name in &input_channels {
        let chain = output.channels.get(channel_name).ok_or_else(|| {
            anyhow::anyhow!("missing DSP chain for CamillaDSP input channel '{channel_name}'")
        })?;
        let prefix = format!("pre_{}", normalize_export_identifier(channel_name));
        let plugins = plugins_for_stage(chain, "pre_route");
        pre_route_filter_names.push(write_camilladsp_filters_for_plugins(
            &mut out,
            &mut manifest,
            &prefix,
            &plugins,
        )?);
    }

    let mut route_filter_names = Vec::with_capacity(graph.routes.len());
    for (route_idx, route) in graph.routes.iter().enumerate() {
        let prefix = camilladsp_route_prefix(route_idx, route);
        let mut filter_names = Vec::new();
        if let Some(freq) = route.high_pass_hz.or(route.low_pass_hz) {
            let output = if route.high_pass_hz.is_some() {
                "high"
            } else {
                "low"
            };
            write_camilladsp_crossover_filter(
                &mut out,
                &mut manifest,
                &format!("{prefix}_crossover"),
                &route.crossover_type,
                freq,
                output,
            )?;
            filter_names.push(format!("{prefix}_crossover"));
        }
        if route.delay_ms.abs() > 0.001 {
            write_camilladsp_delay_filter(
                &mut out,
                &mut manifest,
                &format!("{prefix}_delay"),
                route.delay_ms,
            )?;
            filter_names.push(format!("{prefix}_delay"));
        }
        route_filter_names.push(filter_names);
    }

    let mut post_route_filter_names = Vec::with_capacity(output_channels.len());
    for channel_name in &output_channels {
        let chain = output.channels.get(channel_name).ok_or_else(|| {
            anyhow::anyhow!("missing DSP chain for CamillaDSP output channel '{channel_name}'")
        })?;
        let prefix = format!("post_{}", normalize_export_identifier(channel_name));
        let plugins = plugins_for_stage(chain, "post_route");
        post_route_filter_names.push(write_camilladsp_filters_for_plugins(
            &mut out,
            &mut manifest,
            &prefix,
            &plugins,
        )?);
    }
    writeln!(out)?;

    writeln!(out, "mixers:")?;
    write_camilladsp_route_expand_mixer(&mut out, &mut manifest, graph, input_channels.len())?;
    write_camilladsp_route_sum_mixer(&mut out, &mut manifest, graph, output_channels.len())?;
    writeln!(out)?;

    writeln!(out, "pipeline:")?;
    for (input_idx, (channel_name, filter_names)) in input_channels
        .iter()
        .zip(pre_route_filter_names.iter())
        .enumerate()
    {
        if !filter_names.is_empty() {
            write_camilladsp_pipeline_filter_step(
                &mut out,
                &mut manifest,
                input_idx,
                input_channels.len(),
                filter_names,
                &format!("pre-route channel '{channel_name}' pipeline"),
            )?;
        }
    }
    write_camilladsp_pipeline_mixer_step(&mut out, &mut manifest, "roomeq_route_matrix")?;

    for (route_idx, filter_names) in route_filter_names.iter().enumerate() {
        if !filter_names.is_empty() {
            write_camilladsp_pipeline_filter_step(
                &mut out,
                &mut manifest,
                route_idx,
                graph.routes.len(),
                filter_names,
                &format!("route #{route_idx} pipeline"),
            )?;
        }
    }

    write_camilladsp_pipeline_mixer_step(&mut out, &mut manifest, "roomeq_route_sum")?;
    for (output_idx, (channel_name, filter_names)) in output_channels
        .iter()
        .zip(post_route_filter_names.iter())
        .enumerate()
    {
        if !filter_names.is_empty() {
            write_camilladsp_pipeline_filter_step(
                &mut out,
                &mut manifest,
                output_idx,
                output_channels.len(),
                filter_names,
                &format!("post-route channel '{channel_name}' pipeline"),
            )?;
        }
    }

    manifest.validate()?;
    Ok(out)
}

fn camilladsp_routing_graph(output: &DspChainOutput) -> Option<BassManagementRoutingGraph> {
    output
        .metadata
        .as_ref()
        .and_then(|metadata| metadata.bass_management.as_ref())
        .and_then(|report| report.routing_graph.clone())
        .or_else(|| {
            output.global_plugins.iter().find_map(|plugin| {
                if plugin.plugin_type != "matrix"
                    || plugin
                        .parameters
                        .get("label")
                        .and_then(|label| label.as_str())
                        != Some("home_cinema_bass_management")
                {
                    return None;
                }
                let metadata = plugin.parameters.get("metadata")?;
                let routes: Vec<BassManagementRoute> =
                    serde_json::from_value(metadata.get("routes")?.clone()).ok()?;
                let matrix = Some(BassManagementMatrix {
                    input_channel_map: serde_json::from_value(
                        plugin.parameters.get("input_channel_map")?.clone(),
                    )
                    .ok()?,
                    output_channel_map: serde_json::from_value(
                        plugin.parameters.get("output_channel_map")?.clone(),
                    )
                    .ok()?,
                    matrix: serde_json::from_value(plugin.parameters.get("matrix")?.clone())
                        .ok()?,
                    route_count: routes.len(),
                });
                let input_channels = ordered_route_channels(
                    &routes,
                    |route| route.source_index,
                    |route| &route.source_channel,
                );
                let output_channels = ordered_route_channels(
                    &routes,
                    |route| route.destination_index,
                    |route| &route.destination,
                );
                Some(BassManagementRoutingGraph {
                    physical_sub_output: metadata
                        .get("physical_sub_output")
                        .and_then(|value| value.as_str())
                        .unwrap_or("")
                        .to_string(),
                    input_channels,
                    output_channels,
                    routes,
                    matrix,
                    advisories: serde_json::from_value(
                        metadata
                            .get("advisories")
                            .cloned()
                            .unwrap_or_else(|| serde_json::json!([])),
                    )
                    .unwrap_or_default(),
                })
            })
        })
}

fn ordered_route_channels<'a, F, G>(
    routes: &'a [BassManagementRoute],
    index: F,
    name: G,
) -> Vec<String>
where
    F: Fn(&'a BassManagementRoute) -> usize,
    G: Fn(&'a BassManagementRoute) -> &'a String,
{
    let mut indexed: Vec<(usize, String)> = routes
        .iter()
        .map(|route| (index(route), name(route).clone()))
        .collect();
    indexed.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));
    indexed.dedup_by(|a, b| a.0 == b.0 && a.1 == b.1);
    indexed.into_iter().map(|(_, name)| name).collect()
}

fn plugins_for_stage(chain: &ChannelDspChain, stage: &str) -> Vec<PluginConfigWrapper> {
    chain
        .plugins
        .iter()
        .filter(|plugin| {
            plugin
                .parameters
                .get("room_eq_stage")
                .and_then(|value| value.as_str())
                == Some(stage)
        })
        .cloned()
        .collect()
}

fn camilladsp_route_prefix(route_idx: usize, route: &BassManagementRoute) -> String {
    format!(
        "route_{route_idx}_{}_to_{}",
        normalize_export_identifier(&route.source_channel),
        normalize_export_identifier(&route.destination)
    )
}

fn write_camilladsp_route_expand_mixer(
    out: &mut String,
    manifest: &mut ExportArtifactManifest,
    graph: &BassManagementRoutingGraph,
    input_channels: usize,
) -> anyhow::Result<()> {
    manifest.define_node(ExportNodeKind::Router, "roomeq_route_matrix")?;
    writeln!(out, "  roomeq_route_matrix:")?;
    writeln!(out, "    channels:")?;
    writeln!(out, "      in: {input_channels}")?;
    writeln!(out, "      out: {}", graph.routes.len())?;
    writeln!(out, "    mapping:")?;
    for (route_idx, route) in graph.routes.iter().enumerate() {
        writeln!(out, "    - dest: {route_idx}")?;
        writeln!(out, "      mute: false")?;
        writeln!(out, "      sources:")?;
        writeln!(out, "      - channel: {}", route.source_index)?;
        writeln!(out, "        gain: {:.6}", route.gain_db)?;
        writeln!(out, "        inverted: {}", route.polarity_inverted)?;
        writeln!(out, "        mute: false")?;
        writeln!(out, "        scale: dB")?;
    }
    Ok(())
}

fn write_camilladsp_route_sum_mixer(
    out: &mut String,
    manifest: &mut ExportArtifactManifest,
    graph: &BassManagementRoutingGraph,
    output_channels: usize,
) -> anyhow::Result<()> {
    manifest.define_node(ExportNodeKind::Router, "roomeq_route_sum")?;
    writeln!(out, "  roomeq_route_sum:")?;
    writeln!(out, "    channels:")?;
    writeln!(out, "      in: {}", graph.routes.len())?;
    writeln!(out, "      out: {output_channels}")?;
    writeln!(out, "    mapping:")?;
    for dest_idx in 0..output_channels {
        writeln!(out, "    - dest: {dest_idx}")?;
        writeln!(out, "      mute: false")?;
        writeln!(out, "      sources:")?;
        for (route_idx, route) in graph.routes.iter().enumerate() {
            if route.destination_index == dest_idx {
                writeln!(out, "      - channel: {route_idx}")?;
                writeln!(out, "        gain: 0")?;
                writeln!(out, "        inverted: false")?;
                writeln!(out, "        mute: false")?;
                writeln!(out, "        scale: dB")?;
            }
        }
    }
    Ok(())
}

fn write_camilladsp_pipeline_mixer_step(
    out: &mut String,
    manifest: &mut ExportArtifactManifest,
    name: &str,
) -> anyhow::Result<()> {
    manifest.reference_node(ExportNodeKind::Router, name, "pipeline");
    writeln!(out, "- bypassed: null")?;
    writeln!(out, "  name: {name}")?;
    writeln!(out, "  type: Mixer")?;
    Ok(())
}

fn export_equalizer_apo(output: &DspChainOutput) -> anyhow::Result<String> {
    if let Some(graph) = camilladsp_routing_graph(output)
        && !graph.routes.is_empty()
    {
        return export_equalizer_apo_routed(output, &graph);
    }
    if !output.global_plugins.is_empty() {
        anyhow::bail!(
            "Equalizer APO export cannot represent these global DSP plugins. \
             It supports only the documented static bass-management routing subset; \
             use CamillaDSP or Apply as Graph for this output."
        );
    }
    let mut out = String::new();
    writeln!(out, "# Equalizer APO configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out)?;

    let channels = sorted_channels(output);

    for (ch_name, chain) in &channels {
        let short = channel_short_name(ch_name);
        writeln!(out, "Channel: {short}")?;

        // Collect all plugins from channel + drivers
        let plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();

        // Gain (preamp)
        let gain = extract_gain_db(&plugins);
        if gain.abs() > 0.01 {
            writeln!(out, "Preamp: {gain:+.1} dB")?;
        }

        // Delay
        if let Some(delay) = extract_delay_ms(&plugins) {
            writeln!(out, "Delay: {delay:.3} ms")?;
        }

        // EQ filters
        let filters = extract_eq_filters(&plugins);
        for (i, f) in filters.iter().enumerate() {
            let ft = apo_filter_type(&f.filter_type);
            match f.filter_type.as_str() {
                "lowpass" | "highpass" | "highpassvariableq" => {
                    writeln!(out, "Filter {:2}: ON {ft} Fc {:.0} Hz", i + 1, f.freq)?;
                }
                _ => {
                    writeln!(
                        out,
                        "Filter {:2}: ON {ft} Fc {:.0} Hz Gain {:+.2} dB Q {:.4}",
                        i + 1,
                        f.freq,
                        f.gain_db,
                        f.q
                    )?;
                }
            }
        }

        // Convolution
        let conv_paths = extract_convolution_paths(&plugins);
        for path in &conv_paths {
            writeln!(out, "Convolution: {path}")?;
        }

        writeln!(out)?;
    }

    Ok(out)
}

/// Render the static routing subset that Equalizer APO can express without
/// hidden intermediate buses: each source feeds one route, routes may sum at
/// a destination, and no routed destination is reused as a separate source.
fn export_equalizer_apo_routed(
    output: &DspChainOutput,
    graph: &BassManagementRoutingGraph,
) -> anyhow::Result<String> {
    ensure_equalizer_apo_routing_supported(output, graph)?;

    let mut out = String::new();
    writeln!(out, "# Equalizer APO configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out, "# Static RoomEQ routing graph (Channel/Copy)")?;
    writeln!(out)?;

    let mut filter_index = 1usize;
    for route in &graph.routes {
        let chain = output.channels.get(&route.source_channel).ok_or_else(|| {
            anyhow::anyhow!(
                "Equalizer APO export is missing the pre-route chain for '{}'",
                route.source_channel
            )
        })?;
        writeln!(
            out,
            "Channel: {}",
            channel_short_name(&route.source_channel)
        )?;
        write_equalizer_apo_plugins(
            &mut out,
            &plugins_for_stage(chain, "pre_route"),
            &mut filter_index,
        )?;
        write_equalizer_apo_route_crossover(&mut out, route, &mut filter_index)?;
        if route.delay_ms.abs() > 0.001 {
            writeln!(out, "Delay: {:.3} ms", route.delay_ms)?;
        }
        writeln!(out)?;
    }

    writeln!(
        out,
        "# Route matrix: each source is filtered above, then summed here"
    )?;
    writeln!(out, "Copy:")?;
    for destination in &graph.output_channels {
        let terms: Vec<String> = graph
            .routes
            .iter()
            .filter(|route| route.destination == *destination)
            .map(|route| {
                let gain = if route.polarity_inverted {
                    -route.gain_linear
                } else {
                    route.gain_linear
                };
                format!("{gain:.9}*{}", channel_short_name(&route.source_channel))
            })
            .collect();
        writeln!(
            out,
            "  {} = {}",
            channel_short_name(destination),
            terms.join(" + ")
        )?;
    }
    writeln!(out)?;

    for destination in &graph.output_channels {
        let chain = output.channels.get(destination).ok_or_else(|| {
            anyhow::anyhow!(
                "Equalizer APO export is missing the post-route chain for '{destination}'"
            )
        })?;
        writeln!(out, "Channel: {}", channel_short_name(destination))?;
        write_equalizer_apo_plugins(
            &mut out,
            &plugins_for_stage(chain, "post_route"),
            &mut filter_index,
        )?;
        writeln!(out)?;
    }
    Ok(out)
}

fn ensure_equalizer_apo_routing_supported(
    output: &DspChainOutput,
    graph: &BassManagementRoutingGraph,
) -> anyhow::Result<()> {
    if output.global_plugins.iter().any(|plugin| {
        plugin.plugin_type != "matrix"
            || plugin
                .parameters
                .get("label")
                .and_then(|value| value.as_str())
                != Some("home_cinema_bass_management")
    }) {
        anyhow::bail!(
            "Equalizer APO export cannot represent non-routing global DSP plugins; \
             use CamillaDSP or Apply as Graph."
        );
    }
    let mut source_count = std::collections::HashMap::<&str, usize>::new();
    for route in &graph.routes {
        *source_count.entry(&route.source_channel).or_default() += 1;
        if !output.channels.contains_key(&route.source_channel)
            || !output.channels.contains_key(&route.destination)
        {
            anyhow::bail!(
                "Equalizer APO export cannot route '{}' to '{}': the graph references a missing channel.",
                route.source_channel,
                route.destination
            );
        }
        if route.high_pass_hz.is_some() == route.low_pass_hz.is_some() {
            anyhow::bail!(
                "Equalizer APO export requires each routed branch to have exactly one high-pass or low-pass crossover; route '{}' -> '{}' is not representable.",
                route.source_channel,
                route.destination
            );
        }
        if !matches!(route.crossover_type.as_str(), "LR24" | "LR48") {
            anyhow::bail!(
                "Equalizer APO export supports LR24 and LR48 routed crossovers; route '{}' -> '{}' requests '{}'.",
                route.source_channel,
                route.destination,
                route.crossover_type
            );
        }
    }
    if let Some((source, _)) = source_count.into_iter().find(|(_, count)| *count > 1) {
        anyhow::bail!(
            "Equalizer APO export cannot preserve fan-out from '{source}': route-specific filters need an intermediate bus. Use CamillaDSP or Apply as Graph."
        );
    }
    let source_channels = graph
        .routes
        .iter()
        .map(|route| route.source_channel.as_str())
        .collect::<std::collections::HashSet<_>>();
    if let Some(route) = graph.routes.iter().find(|route| {
        route.destination != route.source_channel
            && source_channels.contains(route.destination.as_str())
    }) {
        anyhow::bail!(
            "Equalizer APO export cannot preserve routed destination '{}' because it is also used as a source and would require an intermediate bus. Use CamillaDSP or Apply as Graph.",
            route.destination
        );
    }
    Ok(())
}

fn write_equalizer_apo_route_crossover(
    out: &mut String,
    route: &BassManagementRoute,
    filter_index: &mut usize,
) -> anyhow::Result<()> {
    let (kind, frequency) = match (route.high_pass_hz, route.low_pass_hz) {
        (Some(frequency), None) => ("HP", frequency),
        (None, Some(frequency)) => ("LP", frequency),
        _ => anyhow::bail!("invalid Equalizer APO routed crossover"),
    };
    if !frequency.is_finite() || frequency <= 0.0 {
        anyhow::bail!("invalid Equalizer APO crossover frequency {frequency}");
    }
    let sections = if route.crossover_type == "LR24" { 2 } else { 4 };
    for _ in 0..sections {
        writeln!(
            out,
            "Filter {:2}: ON {kind} Fc {frequency:.0} Hz Q 0.7071",
            *filter_index
        )?;
        *filter_index += 1;
    }
    Ok(())
}

fn write_equalizer_apo_plugins(
    out: &mut String,
    plugins: &[PluginConfigWrapper],
    filter_index: &mut usize,
) -> anyhow::Result<()> {
    let gain = extract_gain_db(plugins);
    if gain.abs() > 0.01 {
        writeln!(out, "Preamp: {gain:+.1} dB")?;
    }
    if let Some(delay) = extract_delay_ms(plugins) {
        writeln!(out, "Delay: {delay:.3} ms")?;
    }
    for filter in extract_eq_filters(plugins) {
        let kind = apo_filter_type(&filter.filter_type);
        if !matches!(
            filter.filter_type.as_str(),
            "peak"
                | "lowshelf"
                | "highshelf"
                | "lowpass"
                | "highpass"
                | "highpassvariableq"
                | "notch"
                | "bandpass"
                | "allpass"
        ) {
            anyhow::bail!(
                "Equalizer APO does not support '{}' filters",
                filter.filter_type
            );
        }
        if matches!(
            filter.filter_type.as_str(),
            "lowpass" | "highpass" | "highpassvariableq"
        ) {
            writeln!(
                out,
                "Filter {:2}: ON {kind} Fc {:.0} Hz",
                *filter_index, filter.freq
            )?;
        } else {
            writeln!(
                out,
                "Filter {:2}: ON {kind} Fc {:.0} Hz Gain {:+.2} dB Q {:.4}",
                *filter_index, filter.freq, filter.gain_db, filter.q
            )?;
        }
        *filter_index += 1;
    }
    for path in extract_convolution_paths(plugins) {
        writeln!(out, "Convolution: {path}")?;
    }
    Ok(())
}

fn export_easyeffects(output: &DspChainOutput) -> anyhow::Result<String> {
    let channels = sorted_channels(output);

    // Merge all channel EQ filters into one preset (EasyEffects applies globally)
    let mut all_filters = Vec::new();
    let mut min_gain = 0.0f64;

    // Check for convolution/FIR and warn
    let mut has_unsupported = false;

    for (ch_name, chain) in &channels {
        let plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();
        let filters = extract_eq_filters(&plugins);
        let gain = extract_gain_db(&plugins);

        if !extract_convolution_paths(&plugins).is_empty() {
            has_unsupported = true;
            log::warn!(
                "EasyEffects: skipping convolution for channel '{}' (not supported)",
                ch_name
            );
        }

        // Use most negative gain as preamp to prevent clipping
        if gain < min_gain {
            min_gain = gain;
        }

        all_filters.extend(filters);
    }

    if has_unsupported {
        log::warn!("EasyEffects does not support FIR convolution filters; they were skipped");
    }

    // Build JSON preset
    let mut bands = serde_json::Map::new();
    for (i, f) in all_filters.iter().enumerate().take(30) {
        let band_key = format!("band{i}");
        let mut band = serde_json::Map::new();
        band.insert("frequency".to_string(), serde_json::json!(f.freq));
        band.insert("gain".to_string(), serde_json::json!(f.gain_db));
        band.insert("q".to_string(), serde_json::json!(f.q));
        band.insert(
            "type".to_string(),
            serde_json::json!(easyeffects_filter_type(&f.filter_type)),
        );
        band.insert("mode".to_string(), serde_json::json!("RLC (BT)"));
        band.insert("slope".to_string(), serde_json::json!("x1"));
        band.insert("solo".to_string(), serde_json::json!(false));
        band.insert("mute".to_string(), serde_json::json!(false));
        bands.insert(band_key, serde_json::Value::Object(band));
    }

    let preset = serde_json::json!({
        "output": {
            "equalizer#0": {
                "input-gain": min_gain,
                "output-gain": 0.0,
                "num-bands": all_filters.len().min(30),
                "split-channels": false,
                "left": bands,
                "right": bands,
            }
        }
    });

    Ok(serde_json::to_string_pretty(&preset)?)
}

fn export_wavelet(output: &DspChainOutput, sample_rate: f64) -> anyhow::Result<String> {
    let channels = sorted_channels(output);

    let mut has_unsupported = false;

    // Average the response across all channels
    let mut band_gains = [0.0f64; 9];
    let mut n_channels = 0;

    for (ch_name, chain) in &channels {
        let plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();
        let filters = extract_eq_filters(&plugins);
        let gain = extract_gain_db(&plugins);

        if !extract_convolution_paths(&plugins).is_empty() {
            has_unsupported = true;
            log::warn!(
                "Wavelet: skipping convolution for channel '{}' (not supported)",
                ch_name
            );
        }

        // Build Biquad chain and evaluate at each band frequency
        let biquads: Vec<Biquad> = filters
            .iter()
            .map(|f| {
                let ft = parse_biquad_filter_type(&f.filter_type)?;
                Ok(Biquad::new(ft, f.freq, sample_rate, f.q, f.gain_db))
            })
            .collect::<anyhow::Result<_>>()?;

        for (i, &freq) in WAVELET_BANDS.iter().enumerate() {
            let mut db = gain;
            for bq in &biquads {
                db += bq.log_result(freq);
            }
            band_gains[i] += db;
        }
        n_channels += 1;
    }

    if has_unsupported {
        log::warn!("Wavelet does not support FIR convolution filters; they were skipped");
    }

    // Average across channels
    if n_channels > 1 {
        for g in &mut band_gains {
            *g /= n_channels as f64;
        }
    }

    // Format output
    let mut out = String::new();
    writeln!(out, "# Wavelet GraphicEQ")?;
    writeln!(out, "# Generated by roomeq")?;
    write!(out, "GraphicEQ:")?;
    for (i, (&freq, &gain)) in WAVELET_BANDS.iter().zip(band_gains.iter()).enumerate() {
        if i > 0 {
            write!(out, ";")?;
        }
        write!(out, " {:.0} {:.1}", freq, gain)?;
    }
    writeln!(out)?;

    Ok(out)
}

fn export_pipewire(output: &DspChainOutput, _sample_rate: f64) -> anyhow::Result<String> {
    let mut out = String::new();
    writeln!(out, "# PipeWire filter-chain configuration")?;
    writeln!(out, "# Generated by roomeq")?;
    writeln!(out)?;
    writeln!(out, "context.modules = [")?;
    writeln!(out, "  {{ name = libpipewire-module-filter-chain")?;
    writeln!(out, "    args = {{")?;

    let channels = sorted_channels(output);
    let num_channels = channels.len();

    // Build channel position list
    let positions: Vec<&str> = channels
        .iter()
        .map(|(name, _)| channel_short_name(name))
        .collect();
    let positions_str = positions
        .iter()
        .map(|p| format!("\"{}\"", pipewire_channel_position(p)))
        .collect::<Vec<_>>()
        .join(", ");

    // Nodes
    writeln!(out, "      filter.graph = {{")?;
    writeln!(out, "        nodes = [")?;

    let mut all_node_names: Vec<Vec<String>> = Vec::new(); // per-channel node names

    for (ch_idx, (ch_name, chain)) in channels.iter().enumerate() {
        let ch_prefix = format!("ch{}_{}", ch_idx, ch_name.replace(' ', "_"));
        let mut node_names = Vec::new();

        // Collect all plugins
        let all_plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();

        // Gain node
        let gain = extract_gain_db(&all_plugins);
        if gain.abs() > 0.01 {
            let node_name = format!("{ch_prefix}_gain");
            writeln!(
                out,
                "          {{ type = builtin  name = \"{node_name}\"  label = bq_highshelf  control = {{ \"Freq\" = 0  \"Q\" = 1.0  \"Gain\" = {gain:.2} }} }}"
            )?;
            node_names.push(node_name);
        }

        // PipeWire's delay builtin needs its maximum delay in the config
        // section and its active delay in seconds, not samples.
        if let Some(delay_ms) = extract_delay_ms(&all_plugins) {
            let delay_seconds = delay_ms / 1000.0;
            let node_name = format!("{ch_prefix}_delay");
            writeln!(
                out,
                "          {{ type = builtin  name = \"{node_name}\"  label = delay  config = {{ \"max-delay\" = {delay_seconds:.6} }}  control = {{ \"Delay (s)\" = {delay_seconds:.6} }} }}"
            )?;
            node_names.push(node_name);
        }

        // EQ filter nodes
        let filters = extract_eq_filters(&all_plugins);
        for (i, f) in filters.iter().enumerate() {
            let label = pipewire_filter_label(&f.filter_type)?;
            let node_name = format!("{ch_prefix}_eq_{i}");
            match f.filter_type.as_str() {
                "lowpass" | "highpass" | "highpassvariableq" => {
                    writeln!(
                        out,
                        "          {{ type = builtin  name = \"{node_name}\"  label = {label}  control = {{ \"Freq\" = {:.1}  \"Q\" = {:.4} }} }}",
                        f.freq, f.q
                    )?;
                }
                _ => {
                    writeln!(
                        out,
                        "          {{ type = builtin  name = \"{node_name}\"  label = {label}  control = {{ \"Freq\" = {:.1}  \"Q\" = {:.4}  \"Gain\" = {:.2} }} }}",
                        f.freq, f.q, f.gain_db
                    )?;
                }
            }
            node_names.push(node_name);
        }

        all_node_names.push(node_names);
    }

    writeln!(out, "        ]")?;

    // Links: chain nodes sequentially per channel
    writeln!(out, "        links = [")?;
    for nodes in &all_node_names {
        for pair in nodes.windows(2) {
            writeln!(
                out,
                "          {{ output = \"{}:Out\"  input = \"{}:In\" }}",
                pair[0], pair[1]
            )?;
        }
    }
    writeln!(out, "        ]")?;

    // Inputs/outputs
    writeln!(out, "        inputs  = [")?;
    for nodes in &all_node_names {
        if let Some(first) = nodes.first() {
            writeln!(out, "          \"{first}:In\"")?;
        } else {
            // No processing nodes — passthrough
            writeln!(out, "          null")?;
        }
    }
    writeln!(out, "        ]")?;

    writeln!(out, "        outputs = [")?;
    for nodes in &all_node_names {
        if let Some(last) = nodes.last() {
            writeln!(out, "          \"{last}:Out\"")?;
        } else {
            writeln!(out, "          null")?;
        }
    }
    writeln!(out, "        ]")?;

    writeln!(out, "      }}")?; // filter.graph

    // Capture/playback props
    writeln!(out, "      capture.props = {{")?;
    writeln!(out, "        audio.channels = {num_channels}")?;
    writeln!(out, "        audio.position = [ {positions_str} ]")?;
    writeln!(out, "      }}")?;
    writeln!(out, "      playback.props = {{")?;
    writeln!(out, "        audio.channels = {num_channels}")?;
    writeln!(out, "        audio.position = [ {positions_str} ]")?;
    writeln!(out, "      }}")?;

    writeln!(out, "    }}")?; // args
    writeln!(out, "  }}")?; // module
    writeln!(out, "]")?;

    Ok(out)
}

/// Export a DSP chain as a Roon DSP Engine preset.
///
/// Roon's DSP Engine supports per-channel parametric EQ (up to 20 bands),
/// headroom management (preamp gain), and convolution (WAV files).
/// The output is a JSON object with per-channel sections that can be
/// referenced when configuring Roon's DSP Engine manually.
fn export_roon(output: &DspChainOutput) -> anyhow::Result<String> {
    let channels = sorted_channels(output);

    let mut roon = serde_json::Map::new();
    roon.insert(
        "_comment".to_string(),
        serde_json::json!("Roon DSP Engine preset — generated by roomeq"),
    );

    let mut channel_configs = serde_json::Map::new();

    for (ch_name, chain) in &channels {
        let all_plugins: Vec<PluginConfigWrapper> =
            collect_all_plugins(chain).into_iter().cloned().collect();

        let mut ch = serde_json::Map::new();

        // Headroom / preamp gain
        let gain = extract_gain_db(&all_plugins);
        if gain.abs() > 0.01 {
            ch.insert("headroom_gain_db".to_string(), serde_json::json!(gain));
        }

        // Delay (Roon doesn't have a per-channel delay in PEQ, but we include it
        // so the user knows what value to set in Speaker Setup > Distance)
        if let Some(delay_ms) = extract_delay_ms(&all_plugins) {
            ch.insert("delay_ms".to_string(), serde_json::json!(delay_ms));
        }

        // Parametric EQ bands (max 20 per Roon endpoint)
        let filters = extract_eq_filters(&all_plugins);
        let mut bands = Vec::new();
        for f in filters.iter().take(20) {
            let mut band = serde_json::Map::new();
            band.insert(
                "type".to_string(),
                serde_json::json!(roon_filter_type(&f.filter_type)),
            );
            band.insert("frequency".to_string(), serde_json::json!(f.freq));
            band.insert("gain".to_string(), serde_json::json!(f.gain_db));
            band.insert("q".to_string(), serde_json::json!(f.q));
            band.insert("enabled".to_string(), serde_json::json!(true));
            bands.push(serde_json::Value::Object(band));
        }
        if !bands.is_empty() {
            ch.insert(
                "parametric_eq".to_string(),
                serde_json::json!({
                    "bands": bands,
                    "is_enabled": true
                }),
            );
        }

        // Convolution IR files
        let conv_paths = extract_convolution_paths(&all_plugins);
        if !conv_paths.is_empty() {
            ch.insert(
                "convolution".to_string(),
                serde_json::json!({
                    "ir_files": conv_paths,
                    "is_enabled": true
                }),
            );
        }

        channel_configs.insert(ch_name.to_string(), serde_json::Value::Object(ch));
    }

    roon.insert(
        "channels".to_string(),
        serde_json::Value::Object(channel_configs),
    );

    Ok(serde_json::to_string_pretty(&serde_json::Value::Object(
        roon,
    ))?)
}
