// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use super::extract::extract_cea2034_curves_original;
use super::fetch::fetch_measurement_plot_data;
use super::fetch::read_spinorama;
use super::types::Cea2034Data;
use crate::Curve;
use std::collections::HashMap;
use std::error::Error;

/// Load spinorama measurement with full CEA2034 spin data
///
/// This fetches the requested curve and also extracts all CEA2034 curves
/// when the measurement type is CEA2034.
///
/// # Arguments
/// * `speaker` - Speaker name (e.g., "KEF R3")
/// * `version` - Version (e.g., "asr")
/// * `measurement` - Measurement type (e.g., "CEA2034")
/// * `curve_name` - Specific curve to use as primary (e.g., "Listening Window")
///
/// # Returns
/// Tuple of (primary curve, optional spin data)
pub async fn load_spinorama_with_spin(
    speaker: &str,
    version: &str,
    measurement: &str,
    curve_name: &str,
) -> Result<(Curve, Option<Cea2034Data>), Box<dyn Error>> {
    // Handle Estimated In-Room Response specially
    if measurement == "Estimated In-Room Response"
        || (measurement == "CEA2034" && curve_name == "Estimated In-Room Response")
    {
        let plot_data = fetch_measurement_plot_data(speaker, version, "CEA2034").await?;
        let curves = extract_cea2034_curves_original(&plot_data, "CEA2034")?;

        let pir_curve = curves
            .get("Estimated In-Room Response")
            .ok_or_else(|| {
                Box::<dyn Error>::from("Estimated In-Room Response curve not found in CEA2034 data")
            })?
            .clone();

        let spin_data = build_cea2034_data(curves)?;
        return Ok((pir_curve, Some(spin_data)));
    }

    // Standard curve fetch
    let curve = read_spinorama(speaker, version, measurement, curve_name).await?;

    // Extract spin data if CEA2034
    let spin_data = if measurement == "CEA2034" {
        let plot_data = fetch_measurement_plot_data(speaker, version, measurement).await?;
        let curves = extract_cea2034_curves_original(&plot_data, "CEA2034")?;
        Some(build_cea2034_data(curves)?)
    } else {
        None
    };

    Ok((curve, spin_data))
}

/// Build Cea2034Data from curves HashMap
pub fn build_cea2034_data(curves: HashMap<String, Curve>) -> Result<Cea2034Data, Box<dyn Error>> {
    let get_curve = |name: &str| -> Result<Curve, Box<dyn Error>> {
        curves
            .get(name)
            .cloned()
            .ok_or_else(|| Box::<dyn Error>::from(format!("Missing CEA2034 curve: {}", name)))
    };

    let on_axis = get_curve("On Axis")?;
    let listening_window = get_curve("Listening Window")?;
    let early_reflections = get_curve("Early Reflections")?;
    let sound_power = get_curve("Sound Power")?;
    let estimated_in_room = get_curve("Estimated In-Room Response")?;

    // Compute directivity indices
    let er_di = Curve {
        freq: on_axis.freq.clone(),
        spl: &on_axis.spl - &early_reflections.spl,
        phase: None,
        ..Default::default()
    };
    let sp_di = Curve {
        freq: on_axis.freq.clone(),
        spl: &on_axis.spl - &sound_power.spl,
        phase: None,
        ..Default::default()
    };

    Ok(Cea2034Data {
        on_axis,
        listening_window,
        early_reflections,
        sound_power,
        estimated_in_room,
        er_di,
        sp_di,
        curves,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Curve;
    use ndarray::Array1;

    fn make_curve(spl: &[f64]) -> Curve {
        Curve {
            freq: Array1::from_vec(vec![100.0, 500.0, 1000.0]),
            spl: Array1::from_vec(spl.to_vec()),
            phase: None,
            ..Default::default()
        }
    }

    #[test]
    fn build_cea2034_data_computes_indices() {
        let mut curves = HashMap::new();
        for name in [
            "On Axis",
            "Listening Window",
            "Early Reflections",
            "Sound Power",
            "Estimated In-Room Response",
        ] {
            curves.insert(name.to_string(), make_curve(&[80.0, 82.0, 81.0]));
        }
        let data = build_cea2034_data(curves).unwrap();
        assert_eq!(data.on_axis.freq.len(), 3);
        assert_eq!(data.er_di.spl.len(), 3);
        assert_eq!(data.sp_di.spl.len(), 3);
    }

    #[test]
    fn build_cea2034_data_missing_curve_errors() {
        let mut curves = HashMap::new();
        curves.insert("On Axis".to_string(), make_curve(&[80.0, 82.0, 81.0]));
        let result = build_cea2034_data(curves);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("Missing CEA2034 curve"));
    }
}
