// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use crate::{DirectivityCurve, DirectivityData};

/// Extract a single directivity curve at a specific angle
///
/// # Arguments
/// * `directivity` - The full directivity data
/// * `angle` - The desired angle in degrees
/// * `plane` - "horizontal" or "vertical"
///
/// # Returns
/// * Option containing the DirectivityCurve if found
pub fn get_directivity_at_angle<'a>(
    directivity: &'a DirectivityData,
    angle: f64,
    plane: &str,
) -> Option<&'a DirectivityCurve> {
    let curves = match plane.to_lowercase().as_str() {
        "horizontal" | "h" => &directivity.horizontal,
        "vertical" | "v" => &directivity.vertical,
        _ => return None,
    };

    curves.iter().find(|c| (c.angle - angle).abs() < 0.5)
}

/// Get the on-axis response from directivity data
///
/// # Arguments
/// * `directivity` - The full directivity data
/// * `plane` - "horizontal" or "vertical"
///
/// # Returns
/// * Option containing the on-axis DirectivityCurve
pub fn get_on_axis<'a>(
    directivity: &'a DirectivityData,
    plane: &str,
) -> Option<&'a DirectivityCurve> {
    get_directivity_at_angle(directivity, 0.0, plane)
}

/// Get available angles in the directivity data
///
/// # Arguments
/// * `directivity` - The full directivity data
/// * `plane` - "horizontal" or "vertical"
///
/// # Returns
/// * Vector of available angles
pub fn get_available_angles(directivity: &DirectivityData, plane: &str) -> Vec<f64> {
    let curves = match plane.to_lowercase().as_str() {
        "horizontal" | "h" => &directivity.horizontal,
        "vertical" | "v" => &directivity.vertical,
        _ => return Vec::new(),
    };

    curves.iter().map(|c| c.angle).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cea2034::{DirectivityCurve, DirectivityData};
    use ndarray::Array1;

    fn sample_directivity() -> DirectivityData {
        let curve = |angle| DirectivityCurve {
            angle,
            freq: Array1::from_vec(vec![100.0, 1000.0]),
            spl: Array1::from_vec(vec![80.0, 81.0]),
        };
        DirectivityData {
            horizontal: vec![curve(-10.0), curve(0.0), curve(10.0)],
            vertical: vec![curve(-20.0), curve(20.0)],
        }
    }

    #[test]
    fn get_directivity_at_angle_finds_horizontal() {
        let d = sample_directivity();
        let c = get_directivity_at_angle(&d, 0.0, "horizontal").unwrap();
        assert!((c.angle).abs() < 0.01);
    }

    #[test]
    fn get_directivity_at_angle_unknown_plane_returns_none() {
        let d = sample_directivity();
        assert!(get_directivity_at_angle(&d, 0.0, "diagonal").is_none());
    }

    #[test]
    fn get_on_axis_horizontal() {
        let d = sample_directivity();
        let c = get_on_axis(&d, "h").unwrap();
        assert!((c.angle).abs() < 0.01);
    }

    #[test]
    fn get_available_angles_lists_all() {
        let d = sample_directivity();
        let angles = get_available_angles(&d, "vertical");
        assert_eq!(angles.len(), 2);
        assert!(angles.contains(&-20.0));
        assert!(angles.contains(&20.0));
    }
}
