// Auto-generated by r2factor. Manual edits will be overwritten on next split.

/// CEA2034 spin data with all standard curves.
///
/// This is a backward-compatible alias for [`crate::cea2034::SpinoramaBundle`],
/// which is the canonical type that also provides a builder and computes the
/// derived PIR/directivity-index curves.
pub type Cea2034Data = crate::cea2034::SpinoramaBundle;

/// Contour plot data with 2D heatmap structure
///
/// Used for "SPL Horizontal Contour" and "SPL Vertical Contour" measurements
/// which provide full angle range data (-180° to +180°).
#[derive(Debug, Clone)]
pub struct ContourPlotData {
    /// Frequency values (X axis)
    pub freq: Vec<f64>,
    /// Angle values in degrees (Y axis)
    pub angles: Vec<f64>,
    /// SPL values as a 2D grid (row-major: angles × freq)
    pub spl: Vec<f64>,
    /// Number of frequency points
    pub freq_count: usize,
    /// Number of angle points
    pub angle_count: usize,
}
