[package]
name = "autoeq-plot"
version = "0.5.5"
edition = "2024"
description = "HTML+WASM visualizations and report generation for AutoEQ"
license = "GPL-3.0-or-later"
documentation = "https://docs.rs/autoeq-plot"
homepage = "https://github.com/pierreaubert/autoeq"

[lints]
workspace = true

[features]
default = []

[dependencies]
anyhow = { workspace = true }
autoeq-core = { workspace = true }
autoeq-measurements = { workspace = true }
autoeq-optim = { workspace = true }
autoeq-report-wasm = { workspace = true }
math-iir-fir = { workspace = true }
ndarray = { workspace = true }
serde_json = { workspace = true }
