[env]
# Set macOS deployment target to match your system version
MACOSX_DEPLOYMENT_TARGET = "15.0"
# Force OpenBLAS linking
OPENBLAS_LIB = "/opt/homebrew/opt/openblas/lib"
OPENBLAS_INCLUDE = "/opt/homebrew/opt/openblas/include"

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-mmacosx-version-min=15.0",
    "-C", "link-arg=-L/opt/homebrew/opt/openblas/lib",
    "-C", "link-arg=-lopenblas"
]

[target.x86_64-apple-darwin] 
rustflags = [
    "-C", "link-arg=-mmacosx-version-min=15.0",
    "-C", "link-arg=-L/opt/homebrew/opt/openblas/lib",
    "-C", "link-arg=-lopenblas"
]
