[env]
# macOS-specific configuration
MACOSX_DEPLOYMENT_TARGET = "15.0"

# macOS Apple Silicon (M1/M2/M3) - using Accelerate framework
[target.aarch64-apple-darwin]
rustflags = [
    "-C", 'target-cpu=native',
    "-C", "link-arg=-mmacosx-version-min=15.0",
    "-C", "link-arg=-framework", "-C", "link-arg=Accelerate"
]

# macOS Intel - using Accelerate framework
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-mmacosx-version-min=15.0",
    "-C", "link-arg=-framework", "-C", "link-arg=Accelerate"
]

# Linux x86_64 configuration
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-L /usr/lib/x86_64-linux-gnu/openblas64-pthread",
    "-C", "link-arg=-lopenblas64",
]

# Linux ARM64 configuration
[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-L /usr/lib/aarch64-linux-gnu/openblas64-pthread",
  "-C", "link-arg=-lopenblas64"
]

# Windows MSVC x86_64 configuration
[target.x86_64-pc-windows-msvc]
rustflags = [
    # Windows typically uses Intel MKL or OpenBLAS through vcpkg
    # "-C", "-DCMAKE_TOOLCHAIN_FILE=C:/Users/pierr/source/repos/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake",
    # Uncomment and adjust paths if using vcpkg OpenBLAS:
    "-C", "link-arg=/LIBPATH:C:\\vcpkg\\installed\\x64-windows\\lib",
    "-C", "link-arg=/LIBPATH:C:\\Users\\pierr\\source\\repos\\microsoft\\vcpkg\\installed\\x64-windows\\lib",
    "-C", "link-arg=openblas.lib"
]

[target.aarch64-pc-windows-msvc]
rustflags = [
    # Windows typically uses Intel MKL or OpenBLAS through vcpkg
    # Uncomment and adjust paths if using vcpkg OpenBLAS:
    "-C", "link-arg=/LIBPATH:C:\\vcpkg\\installed\\arm64-windows\\lib",
    "-C", "link-arg=/LIBPATH:C:\\Users\\pierr\\source\\repos\\microsoft\\vcpkg\\installed\\arm64-windows\\lib",
    "-C", "link-arg=openblas.lib",
    "-C", "link-arg=nlopt.lib"
]

# Windows GNU x86_64 configuration
[target.x86_64-pc-windows-gnu]
rustflags = [
    # For MinGW/MSYS2 with OpenBLAS
    "-C", "link-arg=-lopenblas"
]

[build]
rustflags = ["-Ctarget-cpu=native"]
