use std::fs::OpenOptions;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

/// Convolution sidecar artifact generated by the Room EQ pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConvolutionArtifactKind {
    Fir,
    ResidualFir,
    ExcessPhaseFir,
    PhaseCorrection,
    BandFir,
}

impl ConvolutionArtifactKind {
    fn suffix(self) -> &'static str {
        match self {
            Self::Fir => "fir",
            Self::ResidualFir => "residual_fir",
            Self::ExcessPhaseFir => "excess_phase_fir",
            Self::PhaseCorrection => "phase_correction",
            Self::BandFir => "band_fir",
        }
    }
}

pub fn convolution_artifact_filename(
    channel_name: &str,
    kind: ConvolutionArtifactKind,
    sample_rate: f64,
) -> String {
    let sample_rate = sample_rate.round().max(1.0) as u32;
    format!(
        "{}_{}_{}hz.wav",
        sanitize_filename_part(channel_name),
        kind.suffix(),
        sample_rate
    )
}

/// Best-effort, non-atomic candidate path for a convolution artifact.
///
/// This only checks `Path::exists` and creates nothing, so two pending
/// reservations for the same directory/channel/kind/rate can return the
/// same path (time-of-check/time-of-use race). Kept for backward
/// compatibility; new code should use [`reserve_convolution_artifact`],
/// which atomically claims the destination.
pub fn reserve_convolution_artifact_path(
    output_dir: &Path,
    channel_name: &str,
    kind: ConvolutionArtifactKind,
    sample_rate: f64,
) -> (String, PathBuf) {
    let filename = convolution_artifact_filename(channel_name, kind, sample_rate);
    let path = output_dir.join(&filename);
    if !path.exists() {
        return (filename, path);
    }

    let stem = filename.trim_end_matches(".wav");
    let mut suffix = 2_u64;
    loop {
        let candidate = format!("{stem}_{suffix:03}.wav");
        let path = output_dir.join(&candidate);
        if !path.exists() {
            return (candidate, path);
        }
        suffix = suffix.saturating_add(1);
    }
}

/// Owned, atomically-claimed destination for a convolution artifact.
///
/// The destination file is created with `create_new(true)` at reservation
/// time, so two pending reservations (including across threads or processes)
/// never return the same path: the loser of a race observes `AlreadyExists`
/// and advances to the next `_NNN` suffix. While the reservation is alive
/// the path is owned by this token; dropping it without persisting removes
/// the placeholder so abandoned reservations do not leak files.
#[derive(Debug)]
pub struct ReservedConvolutionArtifact {
    filename: String,
    path: PathBuf,
    persisted: bool,
}

impl ReservedConvolutionArtifact {
    /// Reserved file name (also suitable for engine sidecar references).
    pub fn filename(&self) -> &str {
        &self.filename
    }

    /// Reserved destination path claimed by this token.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Whether the reservation has been persisted.
    pub fn is_persisted(&self) -> bool {
        self.persisted
    }

    /// Mark the reservation persisted after the caller wrote `path()` itself
    /// (e.g. a third-party WAV writer). Prevents `Drop` cleanup.
    pub fn mark_persisted(&mut self) {
        self.persisted = true;
    }

    /// Atomically replace the placeholder with `contents` via a unique temp
    /// file plus a checked rename, then mark the reservation persisted.
    pub fn persist_bytes(&mut self, contents: &[u8]) -> io::Result<()> {
        persist_atomically(&self.path, contents)?;
        self.persisted = true;
        Ok(())
    }

    /// Explicitly abandon the reservation, removing the placeholder file.
    /// Equivalent to dropping without persisting; provided for readability
    /// at failure sites.
    pub fn abandon(self) {}
}

impl Drop for ReservedConvolutionArtifact {
    fn drop(&mut self) {
        if !self.persisted {
            let _ = std::fs::remove_file(&self.path);
        }
    }
}

/// Atomically reserve a convolution artifact destination.
///
/// Creates the output directory (if missing) and claims the deterministic
/// base filename — or the next free `_NNN` suffix — with an atomic
/// `create_new` placeholder file. Safe under thread/process concurrency and
/// across sanitized-name collisions (distinct channel names that sanitize to
/// the same stem simply take successive suffixes).
pub fn reserve_convolution_artifact(
    output_dir: &Path,
    channel_name: &str,
    kind: ConvolutionArtifactKind,
    sample_rate: f64,
) -> io::Result<ReservedConvolutionArtifact> {
    const MAX_SUFFIX: u64 = 999_999;
    std::fs::create_dir_all(output_dir)?;
    let base = convolution_artifact_filename(channel_name, kind, sample_rate);
    let stem = base.trim_end_matches(".wav").to_string();
    let mut suffix: Option<u64> = None;
    loop {
        let filename = match suffix {
            None => base.clone(),
            Some(n) => format!("{stem}_{n:03}.wav"),
        };
        let path = output_dir.join(&filename);
        match OpenOptions::new().write(true).create_new(true).open(&path) {
            Ok(_) => {
                return Ok(ReservedConvolutionArtifact {
                    filename,
                    path,
                    persisted: false,
                });
            }
            Err(e) if e.kind() == io::ErrorKind::AlreadyExists => {
                let next = match suffix {
                    None => 2,
                    Some(n) => n.saturating_add(1),
                };
                if next > MAX_SUFFIX {
                    return Err(io::Error::other("artifact namespace exhausted"));
                }
                suffix = Some(next);
            }
            Err(e) => return Err(e),
        }
    }
}

/// Identity of a persisted convolution artifact.
///
/// Binds the logical source (channel name, artifact kind, rounded sample
/// rate) to the exact bytes written, so a consumer can detect a
/// wrong-channel or overwritten asset instead of trusting a sanitized
/// filename alone. `content_hash` is a non-cryptographic FNV-1a fingerprint
/// used for change detection within a run, not a security digest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConvolutionArtifactIdentity {
    channel_name: String,
    kind: ConvolutionArtifactKind,
    sample_rate_hz: u32,
    content_len: u64,
    content_hash: u64,
    filename: String,
}

impl ConvolutionArtifactIdentity {
    /// Logical channel name the artifact was generated for.
    pub fn channel_name(&self) -> &str {
        &self.channel_name
    }

    /// Artifact kind the bytes were generated as.
    pub fn kind(&self) -> ConvolutionArtifactKind {
        self.kind
    }

    /// Rounded sample rate the bytes were rendered at.
    pub fn sample_rate_hz(&self) -> u32 {
        self.sample_rate_hz
    }

    /// Byte length of the content this identity was taken over.
    pub fn content_len(&self) -> u64 {
        self.content_len
    }

    /// FNV-1a fingerprint of the content this identity was taken over.
    pub fn content_hash(&self) -> u64 {
        self.content_hash
    }

    /// File name this identity belongs to (owned reservation filename).
    pub fn filename(&self) -> &str {
        &self.filename
    }

    /// Relative path of the artifact: exactly `filename`, never an absolute
    /// path and never containing a parent separator. Relative-path rule:
    /// sidecar references must store this relative form; absolute paths are
    /// a caller-local resolution and must not be persisted.
    pub fn relative_path(&self) -> PathBuf {
        PathBuf::from(&self.filename)
    }

    /// Resolve the relative path inside `output_dir`.
    ///
    /// Ownership rule: a reservation token owns its placeholder path until it
    /// is persisted or abandoned. Callers must only read or publish the
    /// resolved path while holding the matching [`ReservedConvolutionArtifact`]
    /// or after it reports persisted; otherwise the file may belong to a
    /// newer reservation that reused the name.
    pub fn resolve(&self, output_dir: &Path) -> PathBuf {
        output_dir.join(&self.filename)
    }

    /// Check `contents` against this identity without touching the filesystem.
    pub fn matches_bytes(&self, contents: &[u8]) -> bool {
        self.content_len == contents.len() as u64
            && self.content_hash == fingerprint_bytes(contents)
    }

    /// Check the file at `path` against this identity.
    ///
    /// Returns `Ok(false)` when the file is missing or differs, so a stale or
    /// replaced asset reads as a mismatch rather than an error at the call
    /// site; other I/O failures are returned.
    pub fn verify_file(&self, path: &Path) -> io::Result<bool> {
        match std::fs::read(path) {
            Ok(bytes) => Ok(self.matches_bytes(&bytes)),
            Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
            Err(e) => Err(e),
        }
    }
}

/// Describe the exact bytes intended for `reservation`.
///
/// The returned identity binds `channel_name`, `kind` and `sample_rate` to
/// `contents` and to the reservation's claimed filename, closing the gap
/// where a sanitized filename alone could alias two distinct sources (e.g.
/// colliding channel names or a re-render at a different rate reusing a
/// `_NNN` slot after an abandon).
pub fn identify_reservation_contents(
    reservation: &ReservedConvolutionArtifact,
    channel_name: &str,
    kind: ConvolutionArtifactKind,
    sample_rate: f64,
    contents: &[u8],
) -> ConvolutionArtifactIdentity {
    ConvolutionArtifactIdentity {
        channel_name: channel_name.to_string(),
        kind,
        sample_rate_hz: sample_rate.round().max(1.0) as u32,
        content_len: contents.len() as u64,
        content_hash: fingerprint_bytes(contents),
        filename: reservation.filename().to_string(),
    }
}

fn fingerprint_bytes(contents: &[u8]) -> u64 {
    const OFFSET_BASIS: u64 = 0xcbf29ce484222325;
    const PRIME: u64 = 0x100000001b3;
    let mut hash = OFFSET_BASIS;
    for byte in contents {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(PRIME);
    }
    hash
}

static RESERVATION_TMP_COUNTER: AtomicU64 = AtomicU64::new(0);

fn persist_atomically(dest: &Path, contents: &[u8]) -> io::Result<()> {
    let parent = dest.parent().unwrap_or_else(|| Path::new("."));
    let stem = dest
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "artifact.wav".to_string());
    let id = RESERVATION_TMP_COUNTER.fetch_add(1, Ordering::Relaxed);
    let tmp = parent.join(format!(".{stem}.tmp-{}-{id}.wav", std::process::id()));
    if let Err(e) = std::fs::write(&tmp, contents) {
        let _ = std::fs::remove_file(&tmp);
        return Err(e);
    }
    match std::fs::rename(&tmp, dest) {
        Ok(()) => Ok(()),
        // Windows refuses to rename over an existing file (our placeholder).
        // We own that placeholder, so remove it and retry once.
        Err(e) => {
            let _ = std::fs::remove_file(dest);
            match std::fs::rename(&tmp, dest) {
                Ok(()) => Ok(()),
                Err(_) => {
                    let _ = std::fs::remove_file(&tmp);
                    Err(e)
                }
            }
        }
    }
}

fn sanitize_filename_part(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut last_was_separator = false;

    for ch in input.chars() {
        let replacement = if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_') {
            Some(ch)
        } else {
            Some('_')
        };

        if let Some(ch) = replacement {
            if ch == '_' {
                if !last_was_separator && !out.is_empty() {
                    out.push(ch);
                }
                last_was_separator = true;
            } else {
                out.push(ch);
                last_was_separator = false;
            }
        }
    }

    while out.ends_with('_') {
        out.pop();
    }

    if out.is_empty() {
        "channel".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn convolution_artifact_filename_includes_sample_rate() {
        assert_eq!(
            convolution_artifact_filename("Front Left", ConvolutionArtifactKind::Fir, 96_000.0),
            "Front_Left_fir_96000hz.wav"
        );
        assert_eq!(
            convolution_artifact_filename(
                "LFE/Sub",
                ConvolutionArtifactKind::PhaseCorrection,
                44_100.0,
            ),
            "LFE_Sub_phase_correction_44100hz.wav"
        );
    }

    #[test]
    fn reserve_convolution_artifact_path_avoids_existing_files() {
        let dir = tempfile::tempdir().unwrap();
        let existing = dir.path().join("L_fir_96000hz.wav");
        std::fs::write(&existing, b"old").unwrap();

        let (filename, path) = reserve_convolution_artifact_path(
            dir.path(),
            "L",
            ConvolutionArtifactKind::Fir,
            96_000.0,
        );

        assert_eq!(filename, "L_fir_96000hz_002.wav");
        assert_eq!(path, dir.path().join("L_fir_96000hz_002.wav"));
    }

    #[test]
    fn atomic_reservations_yield_distinct_paths() {
        let dir = tempfile::tempdir().unwrap();
        let first =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        let second =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();

        assert_eq!(first.filename(), "L_fir_48000hz.wav");
        assert_eq!(second.filename(), "L_fir_48000hz_002.wav");
        assert_ne!(first.path(), second.path());
        assert!(first.path().exists());
        assert!(second.path().exists());
    }

    #[test]
    fn atomic_reservation_runs_parallel_without_collision() {
        use std::sync::{Arc, Barrier};
        let dir = tempfile::tempdir().unwrap();
        let dir_path = dir.path().to_path_buf();
        let barrier = Arc::new(Barrier::new(8));
        let handles: Vec<_> = (0..8)
            .map(|_| {
                let dir_path = dir_path.clone();
                let barrier = Arc::clone(&barrier);
                std::thread::spawn(move || {
                    barrier.wait();
                    // Return the live token so its placeholder stays claimed
                    // until every thread has reserved.
                    reserve_convolution_artifact(
                        &dir_path,
                        "L",
                        ConvolutionArtifactKind::Fir,
                        48_000.0,
                    )
                    .unwrap()
                })
            })
            .collect();
        let reservations: Vec<_> = handles
            .into_iter()
            .map(|h| h.join().unwrap())
            .collect();
        let mut paths: Vec<_> = reservations
            .iter()
            .map(|r| r.path().to_path_buf())
            .collect();
        paths.sort();
        paths.dedup();
        assert_eq!(paths.len(), 8);
    }

    #[test]
    fn atomic_reservation_separates_sanitized_name_collisions() {
        let dir = tempfile::tempdir().unwrap();
        let first =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        // "L!" sanitizes to the same "L" stem.
        let second =
            reserve_convolution_artifact(dir.path(), "L!", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        assert_ne!(first.path(), second.path());
        assert_eq!(second.filename(), "L_fir_48000hz_002.wav");
    }

    #[test]
    fn abandoned_reservation_frees_its_path() {
        let dir = tempfile::tempdir().unwrap();
        let path = {
            let reservation = reserve_convolution_artifact(
                dir.path(),
                "L",
                ConvolutionArtifactKind::Fir,
                48_000.0,
            )
            .unwrap();
            assert!(reservation.path().exists());
            reservation.abandon();
            dir.path().join("L_fir_48000hz.wav")
        };
        assert!(!path.exists());
        let reused =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        assert_eq!(reused.filename(), "L_fir_48000hz.wav");
    }

    #[test]
    fn atomic_reservation_skips_preexisting_files_and_persists() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("L_fir_48000hz.wav"), b"old").unwrap();
        let mut reservation =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        assert_eq!(reservation.filename(), "L_fir_48000hz_002.wav");
        reservation.persist_bytes(b"new").unwrap();
        assert!(reservation.is_persisted());
        let path = reservation.path().to_path_buf();
        drop(reservation);
        // Persisted reservations survive Drop; pre-existing file untouched.
        assert_eq!(std::fs::read(&path).unwrap(), b"new");
        assert_eq!(
            std::fs::read(dir.path().join("L_fir_48000hz.wav")).unwrap(),
            b"old"
        );
    }

    #[test]
    fn identity_binds_source_and_exact_contents() {
        let dir = tempfile::tempdir().unwrap();
        let reservation =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        let identity = identify_reservation_contents(
            &reservation,
            "L",
            ConvolutionArtifactKind::Fir,
            48_000.0,
            b"rendered-fir",
        );
        assert_eq!(identity.channel_name(), "L");
        assert_eq!(identity.kind(), ConvolutionArtifactKind::Fir);
        assert_eq!(identity.sample_rate_hz(), 48_000);
        assert_eq!(identity.filename(), reservation.filename());
        assert!(identity.matches_bytes(b"rendered-fir"));
        // Same filename inputs but different bytes must not match.
        assert!(!identity.matches_bytes(b"rendered-fir!"));
        assert!(!identity.matches_bytes(b""));
    }

    #[test]
    fn identity_verifies_persisted_file_and_rejects_replacement() {
        let dir = tempfile::tempdir().unwrap();
        let mut reservation =
            reserve_convolution_artifact(dir.path(), "L", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        reservation.persist_bytes(b"v1").unwrap();
        let path = reservation.path().to_path_buf();
        let identity = identify_reservation_contents(
            &reservation,
            "L",
            ConvolutionArtifactKind::Fir,
            48_000.0,
            b"v1",
        );
        assert!(identity.verify_file(&path).unwrap());
        // A wrong-channel overwrite at the same path reads as a mismatch.
        std::fs::write(&path, b"other-channel-bytes").unwrap();
        assert!(!identity.verify_file(&path).unwrap());
        // A missing file reads as a mismatch, not an error.
        assert!(!identity.verify_file(&dir.path().join("nope.wav")).unwrap());
    }

    #[test]
    fn identity_relative_path_stays_relative_and_owned() {
        let dir = tempfile::tempdir().unwrap();
        let reservation =
            reserve_convolution_artifact(dir.path(), "L/R", ConvolutionArtifactKind::Fir, 48_000.0)
                .unwrap();
        let identity = identify_reservation_contents(
            &reservation,
            "L/R",
            ConvolutionArtifactKind::Fir,
            48_000.0,
            b"bytes",
        );
        let relative = identity.relative_path();
        assert!(relative.is_relative());
        assert_eq!(relative, Path::new(identity.filename()));
        assert_eq!(identity.resolve(dir.path()), reservation.path());
        // Sanitized filenames never carry a parent separator.
        assert!(!identity.filename().contains('/'));
        assert!(!identity.filename().contains(".."));
    }
}
