// Auto-generated by r2factor. Manual edits will be overwritten on next split.

use std::path::PathBuf;

/// Domain configuration for selecting an input measurement.
///
/// This is the CLI-independent counterpart of the API/file selection fields
/// from [`crate::cli::Args`].
#[derive(Debug, Clone)]
pub struct InputConfig {
    pub speaker: Option<String>,
    pub version: Option<String>,
    pub measurement: Option<String>,
    pub curve_name: String,
    pub curve_path: Option<PathBuf>,
}

/// Domain configuration for selecting a target curve.
#[derive(Debug, Clone)]
pub struct TargetConfig {
    pub target_path: Option<PathBuf>,
    pub curve_name: String,
}

impl From<&crate::cli::Args> for InputConfig {
    fn from(args: &crate::cli::Args) -> Self {
        Self {
            speaker: args.speaker.clone(),
            version: args.version.clone(),
            measurement: args.measurement.clone(),
            curve_name: args.curve_name.clone(),
            curve_path: args.curve.clone(),
        }
    }
}

impl From<&crate::cli::Args> for TargetConfig {
    fn from(args: &crate::cli::Args) -> Self {
        Self {
            target_path: args.target.clone(),
            curve_name: args.curve_name.clone(),
        }
    }
}
