[build.env]
passthrough = [
    "BROWSER_PATH",
    "WEBDRIVER_PATH",
]

[target.x86_64-unknown-linux-gnu]
dockerfile = "./from_macos_arm/Dockerfile.x86_64-unknown-linux-gnu"
# Force use of Docker
pre-build = []

[target.aarch64-unknown-linux-gnu]
dockerfile = "./from_macos_arm/Dockerfile.aarch64-unknown-linux-gnu"
pre-build = []

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/aarch64-pc-windows-gnu:main"

[target.aarch64-pc-windows-gnu]
image = "ghcr.io/cross-rs/aarch64-pc-windows-gnu:main"

[target.aarch64-pc-windows-msvc]
image = "ghcr.io/cross-rs/aarch64-pc-windows-msvc:main"
